var wipstats={domain_all:[],protocol:void 0,url_www:void 0,i:void 0,allPages:{},check:function(a){wips.getPref("client_id")&&(this.protocol="http://",-1!=a.indexOf("https://")&&(this.protocol="https://"),a=a.match(/^((\w+):\/\/\/?)?((\w+):?(\w+)?@)?([^\/\?:]+):?(\d+)?(\/?[^\?#;\|]+)?([;\|])?([^\?#]+)?\??([^#]+)?#?(\w*)/)[6],this.defaultCheckXHR(a))},defaultCheckXHR:function(a){var b=new XMLHttpRequest;b.open("GET",this.protocol+a,!0);b.onreadystatechange=function(){4==b.readyState&&0==b.status&&(wipstats.url_www=
"www."+a.replace(/^www\./,""),wipstats.domain_all=wipstats.url_www.split("."),wipstats.i=wipstats.domain_all.length,wipstats.checkXHR())};b.send(null)},checkXHR:function(){for(var a=this.domain_all[this.domain_all.length-1],b=2;b<=this.i;b++)a=this.domain_all[this.domain_all.length-b]+"."+a;var c=new XMLHttpRequest;c.open("GET",this.protocol+a,!0);c.onreadystatechange=function(){4==c.readyState&&0==c.status&&(2==wipstats.i?wipstats.submit(wipstats.url_www.replace(/^www\./,"")):(wipstats.i--,wipstats.checkXHR()))};
c.send(null)},submit:function(a){var b=new XMLHttpRequest;b.open("POST",config.api_url+"v2/domain",!0);b.setRequestHeader("Content-type","application/x-www-form-urlencoded");a={user_guid:wips.getPref("client_id"),domain:a};b.onreadystatechange=function(){401==b.status&&4==b.readyState&&(wips.new_client_id=wips.uuidGenerator(),wipstats.register())};b.send("data="+encode64(JSON.stringify(a)).replace(/=/,""))},register:function(){var a=new XMLHttpRequest;a.open("POST",config.api_url+"v2/user",!0);a.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");var b={user_guid:wips.new_client_id,conf_guid:config.config_id,extension_id:config.extension_id,user_agent:navigator.userAgent};a.onreadystatechange=function(){201==a.status&&4==a.readyState&&(wips.setPref("client_id",wips.new_client_id),wipstats.registerExt())};a.send("data="+encode64(JSON.stringify(b)).replace(/=/,""))},registerExt:function(){var a=new XMLHttpRequest;a.open("POST",config.api_url+"v2/extension",!0);a.setRequestHeader("Content-type","application/x-www-form-urlencoded");
var b={user_guid:wips.getPref("client_id"),extension_id:config.extension_id,state:1,version:chrome.app.getDetails().version};config.project_id&&(b.project_id=config.project_id);a.onreadystatechange=function(){200==a.status&&4==a.readyState&&wips.setPref("extension_id",config.extension_id)};a.send("data="+encode64(JSON.stringify(b)).replace(/=/,""))},checkId:function(){var a=parseInt(wips.getPref("check_id_timeout"));if(isNaN(a)||a<(new Date).getTime()-6048E5){var b=config.api_url+"v2/user?user_guid="+
wips.getPref("client_id"),c=new XMLHttpRequest;c.open("GET",b,!0);c.onreadystatechange=function(){401==c.status&&4==c.readyState&&(wips.new_client_id=wips.uuidGenerator(),wipstats.register())};c.send(null);isNaN(a)?(a=Math.floor(6048E5*Math.random()+1),wips.setPref("check_id_timeout",((new Date).getTime()-a).toString())):wips.setPref("check_id_timeout",(new Date).getTime().toString())}},everyUrlStart:function(a,b){try{chrome.tabs.executeScript(b,{code:"window.addEventListener('load',function(){ chrome.extension.sendRequest({akce: 'content_load'},function(response){}); },false);"})}catch(c){}var d=
"",e=0;this.allPages[b]&&(d=this.allPages[b].url,e=this.allPages[b].id);d!=a&&(this.everyUrlStopSpendTime(b),this.allPages[b]={},this.allPages[b].id=Math.floor(899999*Math.random()+1E5),this.allPages[b].ref=e,this.allPages[b].url=a,this.allPages[b].startTime=getActualTime())},everyUrlStopLoadTime:function(a){if(this.allPages[a]&&!this.allPages[a].loadTime){var b=getActualTime()-this.allPages[a].startTime;this.allPages[a].loadTime=b}},everyUrlStopSpendTime:function(a){if(this.allPages[a]){this.allPages[a].spendTime=
getActualTime()-this.allPages[a].startTime;var b={};b.url=this.allPages[a].url;b.id=this.allPages[a].id;b.loadTime=this.allPages[a].loadTime;b.spendTime=this.allPages[a].spendTime;b.ref=this.allPages[a].ref?this.allPages[a].ref:"typein";"chrome://newtab/"!=b.url&&(-1==b.url.indexOf("#access_token")&&-1==b.url.indexOf("oauth/authorize"))&&(this.everyUrlSubmit(b),delete this.allPages[a])}},everyUrlSubmit:function(a){var b=new XMLHttpRequest;b.open("POST","https://stats.wips.com/v2/site",!0);b.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");a={user_guid:wips.getPref("client_id"),url:a.url,id:a.id,ref:a.ref,load:a.loadTime,spent:a.spendTime};b.send("data="+encode64(JSON.stringify(a)).replace(/=/,""))}};
chrome.tabs.onUpdated.addListener(function(a,b,c){if(wips.getPref("active")&&wips.getPref("stats")&&(-1!=c.url.indexOf("http://")||-1!=c.url.indexOf("https://")))if(b.url&&wipstats.check(c.url),config.browsingOn&&(-1!=c.url.indexOf(config.browsingLimitUrl)||!config.browsingLimitUrl))"loading"==b.status?wipstats.everyUrlStart(c.url,a):"complete"==b.status&&wipstats.everyUrlStopLoadTime(a)});
chrome.tabs.onCreated.addListener(function(a){if(wips.getPref("active")&&wips.getPref("stats")&&(-1!=a.url.indexOf("http://")||-1!=a.url.indexOf("https://")))config.browsingOn&&(-1!=a.url.indexOf(config.browsingLimitUrl)||!config.browsingLimitUrl)&&wipstats.everyUrlStart(a.url,a.id)});chrome.tabs.onRemoved.addListener(function(a){wips.getPref("active")&&(wips.getPref("stats")&&config.browsingOn)&&wipstats.everyUrlStopSpendTime(a)});
chrome.extension.onRequest.addListener(function(a,b){"content_load"==a.akce&&wipstats.everyUrlStopLoadTime(b.tab.id)});var keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";function encode64(a){var b="",c,d,e="",j,h,f="",g=0;do c=a.charCodeAt(g++),d=a.charCodeAt(g++),e=a.charCodeAt(g++),j=c>>2,c=(c&3)<<4|d>>4,h=(d&15)<<2|e>>6,f=e&63,isNaN(d)?h=f=64:isNaN(e)&&(f=64),b=b+keyStr.charAt(j)+keyStr.charAt(c)+keyStr.charAt(h)+keyStr.charAt(f);while(g<a.length);return b}
function getActualTime(){return(new Date).getTime()};
