var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};
goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,g=0;d=b[g];g++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.useStrictRequires=!1;goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);if(goog.useStrictRequires)throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=
-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(!goog.isProvided_(f))if(f in d.nameToPath)a(d.nameToPath[f]);else throw Error("Undefined nameToPath for "+f);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){goog.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.getMsgWithFallback=function(a){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===d)g=!0;else if(g)return f.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};goog.MODIFY_FUNCTION_PROTOTYPES=!0;
goog.MODIFY_FUNCTION_PROTOTYPES&&(Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return goog.bind.apply(null,c)}return goog.bind(this,a)},Function.prototype.partial=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return goog.bind.apply(null,b)},Function.prototype.inherits=function(a){goog.inherits(this,a)},Function.prototype.mixin=function(a){goog.mixin(this.prototype,
a)});var gdocs={AnimatedBrowserIcon:function(a,b){this.browserIconPath_=a;this.params_=b;this.numInProgress_=0;this.browserIconCanvas_=document.createElement("canvas");this.context_=this.browserIconCanvas_.getContext("2d");this.image_=new Image;this.image_.src=this.browserIconPath_;this.lastStart_=this.intervalId_=0;this.hasDrawn_=!1}};
gdocs.AnimatedBrowserIcon.prototype.start=function(){0==this.numInProgress_++&&(this.lastStart_=Date.now(),this.animate_(),this.intervalId_=window.setInterval(goog.bind(this.animate_,this),this.params_.getRedrawMsecs()))};gdocs.AnimatedBrowserIcon.prototype.stop=function(){0==--this.numInProgress_&&(window.clearInterval(this.intervalId_),this.intervalId_=0,chrome.browserAction.setIcon({path:this.browserIconPath_}))};
gdocs.AnimatedBrowserIcon.prototype.animate_=function(){if(this.image_.complete){this.hasDrawn_||(this.browserIconCanvas_.width=this.image_.width,this.browserIconCanvas_.height=this.image_.height,this.hasDrawn_=!0);var a=Date.now()-this.lastStart_,a=this.mutate_(a,this.image_.width,this.image_.height);chrome.browserAction.setIcon({imageData:a})}};
gdocs.AnimatedBrowserIcon.prototype.mutate_=function(a,b,c){var d=this.params_.computeScale(a);a=this.params_.computeRadians(a);this.context_.clearRect(0,0,b,c);this.context_.save();this.context_.translate(b/2,c/2);this.context_.globalAlpha=0.8;this.context_.scale(d,d);this.context_.rotate(a);this.context_.translate(-b/2,-c/2);this.context_.drawImage(this.image_,0,0);this.context_.restore();return this.context_.getImageData(0,0,b,c)};gdocs.AnimatedBrowserIconParams=function(a){this.redrawMsecs_=this.val_("redrawMsecs",200,a);this.alphaBegin_=this.val_("alphaBegin",0.1,a);this.alphaEnd_=this.val_("alphaEnd",0.8,a);this.scaleBegin_=this.val_("scaleBegin",0.3,a);this.scaleEnd_=this.val_("scaleEnd",1,a);var b=this.val_("period",4E3,a);this.alphaPhasePeriod_=this.val_("alphaPhasePeriod",b,a);this.scalePhasePeriod_=this.val_("scalePhasePeriod",b,a);this.rotationPeriod_=this.val_("rotationPeriod",b,a)};
gdocs.AnimatedBrowserIconParams.prototype.getRedrawMsecs=function(){return this.redrawMsecs_};gdocs.AnimatedBrowserIconParams.prototype.val_=function(a,b,c){return!c||!goog.isDefAndNotNull(c[a])?b:c[a]};gdocs.AnimatedBrowserIconParams.prototype.computeAlpha=function(a){return this.computeOscilation_(a,this.alphaPhasePeriod_,this.alphaBegin_,this.alphaEnd_)};gdocs.AnimatedBrowserIconParams.prototype.computeScale=function(a){return this.computeOscilation_(a,this.scalePhasePeriod_,this.scaleBegin_,this.scaleEnd_)};
gdocs.AnimatedBrowserIconParams.prototype.computeRadians=function(a){a=this.computePercentComplete_(a,this.rotationPeriod_);return 2*Math.PI*a};gdocs.AnimatedBrowserIconParams.prototype.computeOscilation_=function(a,b,c,d){a=this.computePercentComplete_(a,b);return c+(d-c)*2*(0.5>=a?a:1-a)};gdocs.AnimatedBrowserIconParams.prototype.computePercentComplete_=function(a,b){return a%b/b};gdocs.UploadParams=function(a){this.userImpression_=a};goog.exportSymbol("gdocs.UploadParams",gdocs.UploadParams);gdocs.UploadParams.prototype.getUserImpression=function(){return this.userImpression_};goog.exportProperty(gdocs.UploadParams.prototype,"getUserImpression",gdocs.UploadParams.prototype.getUserImpression);goog.exportProperty(gdocs.UploadParams.prototype,"isUploadOnly",gdocs.UploadParams.prototype.isUploadOnly);gdocs.CaptureUploadParams=function(a,b){gdocs.UploadParams.call(this,b);this.capturer_=a};goog.inherits(gdocs.CaptureUploadParams,gdocs.UploadParams);goog.exportSymbol("gdocs.CaptureUploadParams",gdocs.CaptureUploadParams);gdocs.CaptureUploadParams.prototype.getCapturer=function(){return this.capturer_};goog.exportProperty(gdocs.CaptureUploadParams.prototype,"getCapturer",gdocs.CaptureUploadParams.prototype.getCapturer);gdocs.CaptureUploadParams.prototype.isUploadOnly=function(){return!0};gdocs.DownloadResults=function(a,b){this.contentType_=a;this.blobData_=b};goog.exportSymbol("gdocs.DownloadResults",gdocs.DownloadResults);gdocs.DownloadResults.prototype.getContentType=function(){return this.contentType_};goog.exportProperty(gdocs.DownloadResults.prototype,"getContentType",gdocs.DownloadResults.prototype.getContentType);gdocs.DownloadResults.prototype.getBlobData=function(){return this.blobData_};var gdlog={};goog.exportSymbol("gdlog",gdlog);gdlog.Level={SEVERE:1E3,WARNING:900,INFO:800,CONFIG:700,FINE:500,FINER:400,FINEST:300};gdlog.ENABLE_DEBUG_FLAG=!1;gdlog.DEFAULT_LEVEL_UNCOMPILED_=gdlog.Level.INFO;gdlog.DEFAULT_LEVEL_COMPILED_=gdlog.Level.WARNING;gdlog.loglevel=gdlog.ENABLE_DEBUG_FLAG?gdlog.DEFAULT_LEVEL_UNCOMPILED_:gdlog.DEFAULT_LEVEL_COMPILED_;goog.exportSymbol("gdlog.loglevel",gdlog.loglevel);gdlog.msg_=function(a,b){return a+": "+b};gdlog.isLoggable_=function(a){return a>=gdlog.loglevel};
gdlog.error=function(a,b){window.console.error(gdlog.msg_(a,b))};gdlog.warn=function(a,b){gdlog.isLoggable_(gdlog.Level.WARNING)&&window.console.warn(gdlog.msg_(a,b))};gdlog.info=function(a,b){gdlog.isLoggable_(gdlog.Level.INFO)&&window.console.info(gdlog.msg_(a,b))};gdlog.fine=function(a,b){gdlog.isLoggable_(gdlog.Level.FINE)&&window.console.log(gdlog.msg_(a,b))};gdlog.finer=function(a,b){gdlog.isLoggable_(gdlog.Level.FINER)&&window.console.debug(gdlog.msg_(a,b))};
gdlog.logwarn=function(){return gdlog.setLoggingLevel_(gdlog.Level.WARNING,"WARN")};goog.exportSymbol("gdlog.logwarn",gdlog.logwarn);gdlog.loginfo=function(){return gdlog.setLoggingLevel_(gdlog.Level.INFO,"INFO")};goog.exportSymbol("gdlog.loginfo",gdlog.loginfo);gdlog.logfine=function(){return gdlog.setLoggingLevel_(gdlog.Level.FINE,"FINE")};goog.exportSymbol("gdlog.logfine",gdlog.logfine);gdlog.logfiner=function(){return gdlog.setLoggingLevel_(gdlog.Level.FINER,"FINER")};
goog.exportSymbol("gdlog.logfiner",gdlog.logfiner);gdlog.setLoggingLevel_=function(a,b){gdlog.loglevel=a;return"Log level is now "+b};gdlog.prettyPrint=function(a,b){if(!a)return'""';var c=b||100,d={},e;for(e in a){var g=String(a[e]),f=g.length;f>c&&(g=g.substr(0,c)+" ... ("+f+" bytes)");d[e]=g}return JSON.stringify(d,null,2)};gdocs.UploadPageState=function(a){this.defaultFilename_=a;this.filename_="";this.percentage_=0;this.fatalMsg_=this.uploadPage_=null;this.fatalMsgHasHtml_=!1};gdocs.UploadPageState.prototype.fatal=function(a){gdlog.info("UploadPageState.fatal",a);this.fatalMsg_=this.fatalMsg_?this.fatalMsg_+("; "+a):a;this.uploadPage_&&this.uploadPage_.fatal(this.fatalMsg_,this.fatalMsgHasHtml_)};gdocs.UploadPageState.prototype.fatalHtml=function(a){this.fatalMsgHasHtml_=!0;this.fatal(a)};
gdocs.UploadPageState.prototype.hasFailed=function(){return!!this.fatalMsg_};gdocs.UploadPageState.prototype.isCancel=function(){return!!this.uploadPage_&&this.uploadPage_.isCancel()};gdocs.UploadPageState.prototype.clearCancel=function(){this.uploadPage_&&this.uploadPage_.clearCancel()};gdocs.UploadPageState.prototype.setUploadPage=function(a){this.uploadPage_=a;this.fatalMsg_?this.uploadPage_.fatal(this.fatalMsg_,this.fatalMsgHasHtml_):this.updateFilename_()};
gdocs.UploadPageState.prototype.setPercent=function(a){this.percentage_=a;this.uploadPage_&&this.uploadPage_.setPercent(this.percentage_)};gdocs.UploadPageState.prototype.setFilename=function(a){this.filename_=a;this.uploadPage_&&this.updateFilename_()};gdocs.UploadPageState.prototype.getFilename=function(){return this.filename_?this.filename_:this.defaultFilename_};
gdocs.UploadPageState.prototype.updateFilename_=function(){var a=this.filename_?chrome.i18n.getMessage("DOWNLOAD_KNOWN_NAME",this.filename_):chrome.i18n.getMessage("DOWNLOAD_UNKNOWN_NAME");this.uploadPage_.updateProgressText(a)};gdocs.DriveDataController=function(a,b,c,d){this.tab_=b;this.uploadPageState_=new gdocs.UploadPageState(c);this.allowConvert_=d&&a.getOptions().getConvertToGoogleFormat();this.resumableUploader_=this.fatalMsg_=this.downloadResults_=null};goog.exportSymbol("gdocs.DriveDataController",gdocs.DriveDataController);gdocs.DriveDataController.prototype.getTab=function(){return this.tab_};gdocs.DriveDataController.prototype.getAllowConvert=function(){return this.allowConvert_};
goog.exportProperty(gdocs.DriveDataController.prototype,"getAllowConvert",gdocs.DriveDataController.prototype.getAllowConvert);gdocs.DriveDataController.prototype.setResumableUploader=function(a){this.resumableUploader_=a};goog.exportProperty(gdocs.DriveDataController.prototype,"setResumableUploader",gdocs.DriveDataController.prototype.setResumableUploader);
gdocs.DriveDataController.prototype.uploadBlob=function(a,b){gdlog.info("DriveDataController.uploadBlob","Blob size:"+a.size+" contentType:"+b);0>=a.size?this.fatal(chrome.i18n.getMessage("DOWNLOAD_FAILURE_NO_DATA")):(this.downloadResults_=new gdocs.DownloadResults(b,a),this.resumableUploader_&&this.resumableUploader_.startResumableUpload())};
gdocs.DriveDataController.prototype.createDataUriBlob=function(a,b){if(b){a=window.atob(a);for(var c=new Uint8Array(new ArrayBuffer(a.length)),d=0;d<a.length;d++)c[d]=a.charCodeAt(d);c=new DataView(c.buffer);return this.createBlob(c)}return this.createBlob(decodeURI(a))};gdocs.DriveDataController.prototype.createBlob=function(a){return new Blob([a])};gdocs.DriveDataController.prototype.getDownloadResults=function(){return this.downloadResults_};
goog.exportProperty(gdocs.DriveDataController.prototype,"getDownloadResults",gdocs.DriveDataController.prototype.getDownloadResults);gdocs.DriveDataController.prototype.setFilename=function(a){this.uploadPageState_.setFilename(a)};gdocs.DriveDataController.prototype.getFilename=function(){return this.uploadPageState_.getFilename()};goog.exportProperty(gdocs.DriveDataController.prototype,"getFilename",gdocs.DriveDataController.prototype.getFilename);gdocs.DriveDataController.prototype.fatal=function(a){this.uploadPageState_.fatal(a)};
gdocs.DriveDataController.prototype.fatalHtml=function(a){this.uploadPageState_.fatalHtml(a)};gdocs.DriveDataController.prototype.hasFailed=function(){return this.uploadPageState_.hasFailed()};goog.exportProperty(gdocs.DriveDataController.prototype,"hasFailed",gdocs.DriveDataController.prototype.hasFailed);gdocs.DriveDataController.prototype.setPercent=function(a){this.uploadPageState_.setPercent(a)};gdocs.DriveDataController.prototype.isCancel=function(){return this.uploadPageState_.isCancel()};
gdocs.DriveDataController.prototype.clearCancel=function(){this.uploadPageState_.clearCancel()};gdocs.DriveDataController.prototype.setUploadPage=function(a){this.uploadPageState_.setUploadPage(a)};goog.exportProperty(gdocs.DriveDataController.prototype,"setUploadPage",gdocs.DriveDataController.prototype.setUploadPage);gdocs.Capturer=function(a,b,c,d){gdocs.DriveDataController.call(this,a,b,c,d)};goog.inherits(gdocs.Capturer,gdocs.DriveDataController);goog.exportSymbol("gdocs.Capturer",gdocs.Capturer);gdocs.Capturer.createFilenameFromTab=function(a,b){var c=a.title;b&&(c+=b);return c};gdocs.GOOGLE_DOCS_ROOT_URL="https://docs.google.com/";gdocs.IMPRESSION={OTHER:0,LINK:2,IMAGE:3,AUDIO:4,VIDEO:5,PAGE_ACTION_URL:6,PAGE_ACTION_DOC:7,PAGE_ACTION_HTML:8,PAGE_ACTION_CAPTURE_IMAGE_VISIBLE:9,PAGE_ACTION_CAPTURE_MHTML:10,DATA_WEB_INTENT:13,URL_WEB_INTENT:14,PAGE_ACTION_CAPTURE_IMAGE_ENTIRE:15};gdocs.HttpStatus={OK:200,CREATED:201,ACCEPTED:202,RESUME_INCOMPLETE:308,UNAUTHORIZED:401};gdocs.IMPRESSION_HEADER="X-DocsExt-Action";
gdocs.impressionHeader=function(a,b){var c=b||{};c[gdocs.IMPRESSION_HEADER]=a.toString();return c};gdocs.MAX_GENERATED_TITLE_LEN=50;gdocs.MAX_SUFFIX_LEN=8;gdocs.UPLOAD_CHUNK_SIZE=262144;gdocs.KEYCODE_ESCAPE="27";gdocs.MIME_TYPE={ATOM:"application/atom+xml",HTML:"text/html",MHTML:"text/mhtml",OCTET_STREAM:"application/octet-stream",PLAIN:"text/plain",PDF:"application/pdf",PNG:"image/png",X_PDF:"application/x-pdf",XML:"text/xml"};
gdocs.EXTENSIONS={"application/msword":"doc","application/pdf":"pdf","application/rtf":"rtf","application/vnd.ms-excel":"xls","application/vnd.ms-powerpoint":"ppt","application/vnd.openxmlformats-officedocument.presentationml.presentation":"pptx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"xlsx","application/vnd.openxmlformats-officedocument.wordprocessingml.document":".docx","application/x-gzip":"gzip","application/x-pdf":"pdf","application/zip":"zip","audio/mp4":"mp4","audio/mpeg":"mp3",
"audio/ogg":"ogg","audio/vnd.wave":"wav","image/gif":"gif","image/jpeg":"jpg","image/pjpeg":"jpg","image/png":"png","image/svg+xml":"svg","image/tiff":"tif","image/vnd.microsoft.icon":"ico","text/css":"css","text/csv":"csv","text/html":"html","text/mhtml":"mht","text/plain":"txt","text/tsv":"tsv","text/xml":"xml","video/mp4":"mp4","video/mpeg":"mpg","video/ogg":"ogg"};
gdocs.CONVERTIBLE={"application/msword":!0,"application/rtf":!0,"application/vnd.ms-excel":!0,"application/vnd.ms-powerpoint":!0,"application/vnd.openxmlformats-officedocument.presentationml.presentation":!0,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":!0,"application/vnd.openxmlformats-officedocument.wordprocessingml.document":!0,"text/csv":!0,"text/html":!0,"text/plain":!0,"text/tsv":!0};
gdocs.ACTION_ID={BUG_INTERNAL:"bug-internal",FEEDBACK_INTERNAL:"feedback-internal",HELP:"help",HTML:"html",HTML_DOC:"htmldoc",IMAGE_ENTIRE:"image-entire",IMAGE_VISIBLE:"image-visible",MHTML:"mhtml",OPTIONS:"options",SEND_FEEDBACK:"send-feedback",URL:"url"};gdocs.createXhrErrMsg=function(a){var b=a.statusText;b||(b=chrome.i18n.getMessage("UNSPECIFIED_ERROR"));a.status&&(b+=" ("+a.status+")");return b};
gdocs.xmlEncode=function(a){return a.replace(/\&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\'/g,"&apos;").replace(/\"/g,"&quot;")};gdocs.createBaseFilenameFromContentType=function(a){a=a.toLowerCase();return 0==a.indexOf("image")?chrome.i18n.getMessage("IMAGE_DEFAULT_FILENAME"):0==a.indexOf("video")?chrome.i18n.getMessage("VIDEO_DEFAULT_FILENAME"):0==a.indexOf("audio")?chrome.i18n.getMessage("AUDIO_DEFAULT_FILENAME"):chrome.i18n.getMessage("DEFAULT_FILENAME")};gdocs.TitleComputer=function(a,b,c){if(0>=a)throw Error("Maximum title length must be > 0");if(0>b)throw Error("Maximum suffix length must be >= 0");if(b>=a)throw Error("Maximum suffix length must be less than Maximum title length");this.maxTitleLen_=a;this.maxSuffixLen_=b;this.addExtension_=c};gdocs.TitleComputer.TRIM_=/^\s+|\s+$/g;gdocs.TitleComputer.COLLAPSE_SPACES_=/\s+/g;gdocs.TitleComputer.STRIP_META_=/<meta[^>]+>/img;gdocs.TitleComputer.TITLE_CONTENTS_=/<title>\s*([\s\S]+?)\s*<\/title/im;
gdocs.TitleComputer.prototype.createTitleFromText=function(a,b){var c=this.unescapeHtml_(a);if(!c)return null;c=c.replace(gdocs.TitleComputer.COLLAPSE_SPACES_," ");c=c.replace(gdocs.TitleComputer.TRIM_,"");if(!c.length)return null;var c=this.appendContentTypeExtension_(c,b),d="";if(c.length>this.maxTitleLen_){var e=this.splitExtension_(c),g=this.maxTitleLen_;e[1]&&(c=e[0],d="."+e[1],g-=d.length);c=c.substr(0,g);e=Math.max(c.lastIndexOf(" "),c.lastIndexOf("-"),c.lastIndexOf("_"));0<e&&(e=c.substr(0,
e),0<e.length&&(c=e))}return c+d};gdocs.TitleComputer.prototype.splitExtension_=function(a){var b=a.lastIndexOf(".");if(0<b&&b+1!=a.length&&a.length-b-1<=this.maxSuffixLen_){var c=a.substr(b+1);return[a.substr(0,b),c]}return[a,""]};
gdocs.TitleComputer.prototype.appendContentTypeExtension_=function(a,b){if(!b||!this.addExtension_)return a;var c=gdocs.EXTENSIONS[b];if(!c)return gdlog.info("TitleComputer.appendContentTypeExtension","No extension mapping for "+b),a;var d=this.splitExtension_(a);return d[1].toLocaleLowerCase()!=c?a+"."+c:d[0]+"."+c};
gdocs.TitleComputer.prototype.unescapeHtml_=function(a){if(!a)return null;a=a.replace(gdocs.TitleComputer.STRIP_META_,"");var b=document.createElement("body");b.innerHTML=a;for(a=b;a.firstChild;)a=a.firstChild;return a.nodeValue};gdocs.TitleComputer.prototype.createDefaultTitle=function(a,b,c,d,e){return 0==c.indexOf(gdocs.MIME_TYPE.HTML)?(e=this.createFromHtml(e))?e:d?this.createNoData_(a,c,b):null:this.createNoData_(a,c,b)};
gdocs.TitleComputer.prototype.createFromHtml=function(a){a=a.match(gdocs.TitleComputer.TITLE_CONTENTS_);return!a||2>a.length?null:this.createTitleFromText(a[1],gdocs.MIME_TYPE.HTML)};
gdocs.TitleComputer.prototype.createNoData_=function(a,b,c){var d=a.lastIndexOf("/");if(d+1==a.length)return c=this.createNoUrlDefaultTitle_(b,c),this.appendContentTypeExtension_(c,b);a=a.substr(d+1);return 0<=a.indexOf("?")||0==a.indexOf("&")?(c=this.createNoUrlDefaultTitle_(b,c),this.appendContentTypeExtension_(c,b)):this.createTitleFromText(decodeURI(a),b)};
gdocs.TitleComputer.prototype.createNoUrlDefaultTitle_=function(a,b){return 0==a.indexOf(gdocs.MIME_TYPE.PDF)?chrome.i18n.getMessage("PDF_DEFAULT_FILENAME"):0==a.indexOf(gdocs.MIME_TYPE.HTML)?chrome.i18n.getMessage("HTML_DEFAULT_FILENAME"):0==a.indexOf(gdocs.MIME_TYPE.XML)?chrome.i18n.getMessage("XML_DEFAULT_FILENAME"):0==a.indexOf("text")?chrome.i18n.getMessage("TEXT_DEFAULT_FILENAME"):0==a.indexOf("video")?chrome.i18n.getMessage("VIDEO_DEFAULT_FILENAME"):0==a.indexOf("audio")?chrome.i18n.getMessage("AUDIO_DEFAULT_FILENAME"):
0==a.indexOf("image")?chrome.i18n.getMessage("IMAGE_DEFAULT_FILENAME"):b};gdocs.DataUriCapturer=function(a,b,c,d,e){gdocs.Capturer.call(this,a,b,d,!0);this.uri_=c;this.isDefaultFilename_=e};goog.inherits(gdocs.DataUriCapturer,gdocs.Capturer);gdocs.DataUriCapturer.DATA_URI_=/^data:([^,]*),(.*)/i;
gdocs.DataUriCapturer.prototype.startCapture=function(){var a=this.uri_.match(gdocs.DataUriCapturer.DATA_URI_);if(!a||3!=a.length||!a[2])gdlog.warn("DataUriCapturer.startCapture","URI did not parse. URI:"+this.uri_+" matches:"+gdlog.prettyPrint(a)),this.fatal(chrome.i18n.getMessage("DOWNLOAD_FAILURE_NO_DATA"));this.uploadDataUri_(a[1],a[2])};
gdocs.DataUriCapturer.prototype.uploadDataUri_=function(a,b){for(var c=!1,d=gdocs.MIME_TYPE.PLAIN,e=a.split(";"),g=0;g<e.length;g++){var f=e[g]||"",f=f.toLowerCase();"base64"==f?c=!0:0!=f.indexOf("charset=")&&-1!=f.indexOf("/")&&(d=f)}this.isDefaultFilename_&&(e=gdocs.createBaseFilenameFromContentType(d),(e=(new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,!0)).createTitleFromText(e,d))&&this.setFilename(e));c=this.createDataUriBlob(b,c);this.uploadBlob(c,d)};gdocs.RedirectDetector=function(a){this.seenEnoughData_=!1;this.url_="";this.compute_(a)};gdocs.RedirectDetector.PREAMBLE_="<script>window.googleJavaScriptRedirect=1\x3c/script>";gdocs.RedirectDetector.MAX_CONVERT_LEN_=2048;gdocs.RedirectDetector.REDIRECT_SCRIPT_CONTENTS_=/<script>window.googleJavaScriptRedirect=1<\/script>(<META [^>]*>)?<script>([^<>]*)<\/script>/;gdocs.RedirectDetector.SEARCH_RESULT_URL_=/.*\.navigateTo\(window\.parent,window,"([^"]+)"\).*/;
gdocs.RedirectDetector.prototype.hasEnoughData=function(){return this.seenEnoughData_};gdocs.RedirectDetector.prototype.getRedirectUrl=function(){return this.url_};
gdocs.RedirectDetector.prototype.compute_=function(a){if(!a||0==a.byteLength)this.seenEnoughData_=!1;else{a=this.initalStr_(a);var b=Math.min(a.length,gdocs.RedirectDetector.PREAMBLE_.length),b=gdocs.RedirectDetector.PREAMBLE_.substr(0,b);0!=a.indexOf(b)?(this.url_="",this.seenEnoughData_=!0):(a=a.match(gdocs.RedirectDetector.REDIRECT_SCRIPT_CONTENTS_),!a||0==a.length?this.seenEnoughData_=!1:(this.seenEnoughData_=!0,this.extractUrl_(a[0])))}};
gdocs.RedirectDetector.prototype.initalStr_=function(a){var b=Math.min(a.byteLength,gdocs.RedirectDetector.MAX_CONVERT_LEN_);a=new Uint8Array(a,0,b);return String.fromCharCode.apply(null,a)};gdocs.RedirectDetector.prototype.extractUrl_=function(a){a=a.match(gdocs.RedirectDetector.SEARCH_RESULT_URL_);this.url_=!a||2!=a.length?"":a[1]};gdocs.UrlDownloader=function(a,b,c,d,e,g){gdocs.DriveDataController.call(this,a,c,d,g);this.url_=b;this.isDefaultFilename_=e;this.contentType_=this.computedFilename_="";this.numProgressEvents_=this.percentage_=0;this.seenFirstRedirect_=!1};goog.inherits(gdocs.UrlDownloader,gdocs.DriveDataController);goog.exportSymbol("gdocs.UrlDownloader",gdocs.UrlDownloader);gdocs.UrlDownloader.LOAD_EVENT="load";gdocs.UrlDownloader.PROGRESS_EVENT="progress";gdocs.UrlDownloader.STRIP_TO_FINAL_SLASH_=/.*\//;
gdocs.UrlDownloader.FILENAME_PARM_=/;\s*filename=".*?([^/]+)"/;gdocs.UrlDownloader.MAXIMUM_DOWNLOAD_SIZE_=52428800;gdocs.UrlDownloader.MAX_TITLE_SEARCH_BYTES_=32768;
gdocs.UrlDownloader.prototype.updatePercent_=function(a){this.numProgressEvents_++;if(a.type==gdocs.UrlDownloader.LOAD_EVENT)this.markUploadDone_();else if(!(49<=this.percentage_)){a=a.lengthComputable?50*a.loaded/a.total:this.percentage_+this.decayingInc_();var b=Math.min(Math.floor(a),49);b>this.percentage_&&this.setPercent(b);a>this.percentage_&&(this.percentage_=a)}};gdocs.UrlDownloader.prototype.markUploadDone_=function(){this.percentage_=50;this.setPercent(this.percentage_)};
gdocs.UrlDownloader.prototype.decayingInc_=function(){return 15>=this.numProgressEvents_?1:35>=this.numProgressEvents_?0.25:45>=this.numProgressEvents_?0.05:0.01};gdocs.UrlDownloader.prototype.startDownload=function(a){0==this.url_.indexOf("file://")?chrome.extension.isAllowedFileSchemeAccess(goog.bind(this.handleAllowedAccess_,this,a)):0!=this.url_.indexOf("http://")&&0!=this.url_.indexOf("https://")?this.fatal(chrome.i18n.getMessage("INVALID_URL",this.url_)):this.beginDownload_(a)};
gdocs.UrlDownloader.prototype.beginDownload_=function(a){a.addEventListener(gdocs.UrlDownloader.PROGRESS_EVENT,goog.bind(this.onProgress_,this),!1);a.addEventListener(gdocs.UrlDownloader.LOAD_EVENT,goog.bind(this.onLoad_,this),!1);a.open("GET",this.url_,!0);this.addRangeHeader_(a);a.responseType="arraybuffer";try{a.send()}catch(b){this.fatal(chrome.i18n.getMessage("START_DOWNLOAD_EXCEPTION",b.toString()))}};
gdocs.UrlDownloader.prototype.handleAllowedAccess_=function(a,b){b?this.beginDownload_(a):this.fatal(chrome.i18n.getMessage("ENABLE_FILE_URL"))};gdocs.UrlDownloader.prototype.addRangeHeader_=function(a){a.setRequestHeader("Range","bytes=0-"+(0+gdocs.UrlDownloader.MAXIMUM_DOWNLOAD_SIZE_-1))};
gdocs.UrlDownloader.prototype.onProgress_=function(a){if(!this.hasFailed()){var b=a.currentTarget;if(this.shouldStop_(b))b.abort();else if(this.isCancel())this.fatal(chrome.i18n.getMessage("DOWNLOAD_CANCELED")),b.abort(),this.clearCancel();else if(this.isTooLargeFatal_(b))b.abort();else if(400<=b.status)this.fatal(chrome.i18n.getMessage("DOWNLOAD_FAILURE",gdocs.createXhrErrMsg(b)));else{if(!this.computedFilename_&&this.isDefaultFilename_&&(b=this.createTitle_(b)))this.computedFilename_=b,gdlog.fine("UrlDownloader.onProgress",
"filename:"+this.computedFilename_),this.setFilename(this.computedFilename_);this.updatePercent_(a)}}};
gdocs.UrlDownloader.prototype.onLoad_=function(a){if(!this.hasFailed())if(this.isCancel())this.fatal(chrome.i18n.getMessage("DOWNLOAD_CANCELED")),this.clearCancel();else{var b=a.currentTarget;if(!this.shouldStop_(b)&&!this.isTooLargeFatal_(b))if(200!=b.status&&206!=b.status&&(0!=b.status||0!=this.url_.indexOf("file://")))this.fatal(chrome.i18n.getMessage("DOWNLOAD_FAILURE",gdocs.createXhrErrMsg(b)));else{var c=this.getContentType_(b);!this.computedFilename_&&this.isDefaultFilename_&&(this.computedFilename_=
this.createTitle_(b)||this.getFilename(),this.setFilename(this.computedFilename_));this.updatePercent_(a);a=new DataView(b.response);a=this.createBlob(a);this.uploadBlob(a,c)}}};
gdocs.UrlDownloader.prototype.shouldStop_=function(a){if(0!=this.getContentType_(a).indexOf("text/html"))return!1;if(!this.seenRedirect_){a=new gdocs.RedirectDetector(a.response);if(!a.hasEnoughData())return!1;this.seenRedirect_=!0;if(a=a.getRedirectUrl())return this.startRedirect_(a),!0}a=chrome.i18n.getMessage("USE_BROWSER_ACTION_TITLE");var b=chrome.i18n.getMessage("USE_BROWSER_ACTION",this.url_);a='<img class="use-browser-action-img" src="'+chrome.extension.getURL("images/savearrow.png")+'"><div class="use-browser-action-msg">  <div class="use-browser-action-title">'+
a+'</div>  <div class="use-browser-action-body">'+b+"</div></div>";this.fatalHtml(a);return!0};gdocs.UrlDownloader.prototype.startRedirect_=function(a){this.seenFirstRedirect_=!0;this.url_=a;this.contentType_=this.computedFilename_="";this.numProgressEvents_=0;this.startDownload(new XMLHttpRequest)};
gdocs.UrlDownloader.prototype.isTooLargeFatal_=function(a){a=a.getResponseHeader("Content-Range");if(!a)return!1;var b=a.replace(gdocs.UrlDownloader.STRIP_TO_FINAL_SLASH_,"");return b>=gdocs.UrlDownloader.MAXIMUM_DOWNLOAD_SIZE_?(gdlog.info("UrlDownloader.isTooLargeFatal","Too large size:"+b+" contentRange:"+a),this.fatal(chrome.i18n.getMessage("DOWNLOAD_FAILURE_TOO_BIG_MB",Math.floor(b/1048576).toString())),!0):!1};
gdocs.UrlDownloader.prototype.createTitle_=function(a){var b=this.getContentType_(a),c=!this.getAllowConvert()||!(b in gdocs.CONVERTIBLE),c=new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,c),d=this.getContentDisposition_(a);if(d)return c.createTitleFromText(d,b);d="";if(a.response&&0==b.indexOf(gdocs.MIME_TYPE.HTML))for(var e=new Uint8Array(a.response),g=Math.min(e.length,gdocs.UrlDownloader.MAX_TITLE_SEARCH_BYTES_),f=0;f<g;f++){var i=String.fromCharCode(e[f]),d=d+i;if(">"==
i&&16<=f&&"</title>"==d.substr(f-8+1,8).toLowerCase())break}return c.createDefaultTitle(this.url_,this.getFilename(),b,4==a.readyState,d)};gdocs.UrlDownloader.prototype.getContentDisposition_=function(a){if(a=a.getResponseHeader("Content-Disposition"))if((a=a.match(gdocs.UrlDownloader.FILENAME_PARM_))&&1<a.length&&a[1])return a[1];return null};
gdocs.UrlDownloader.prototype.getContentType_=function(a){this.contentType_||((this.contentType_=a.getResponseHeader("Content-Type"))?this.contentType_=this.contentType_.toLowerCase():(this.contentType_=gdocs.MIME_TYPE.OCTET_STREAM,gdlog.info("UrlDownloader.getContentType","No Content-Type, using "+this.contentType_)));return this.contentType_};gdocs.UrlUploadParams=function(a,b){gdocs.UploadParams.call(this,b);this.urlDownloader_=a};goog.inherits(gdocs.UrlUploadParams,gdocs.UploadParams);goog.exportSymbol("gdocs.UrlUploadParams",gdocs.UrlUploadParams);gdocs.UrlUploadParams.prototype.getUrlDownloader=function(){return this.urlDownloader_};goog.exportProperty(gdocs.UrlUploadParams.prototype,"getUrlDownloader",gdocs.UrlUploadParams.prototype.getUrlDownloader);gdocs.UrlUploadParams.prototype.isUploadOnly=function(){return!1};gdocs.DownloadStarter={};gdocs.DownloadStarter.startUrlDownload=function(a,b,c,d,e,g,f){if(0==b.toLowerCase().indexOf("data:"))return a=new gdocs.DataUriCapturer(a,c,b,g,f),a.startCapture(),new gdocs.CaptureUploadParams(a,e);a=new gdocs.UrlDownloader(a,b,c,g,f,d);a.startDownload(new XMLHttpRequest);return new gdocs.UrlUploadParams(a,e)};gdocs.HtmlScrapeCapturer=function(a,b,c){gdocs.Capturer.call(this,a,b,gdocs.HtmlScrapeCapturer.createDefaultFilename_(b,c),!c);this.contentScript_=c?"js/contentscriptraw.js":"js/contentscriptexpand.js";this.callback_=null};goog.inherits(gdocs.HtmlScrapeCapturer,gdocs.Capturer);gdocs.HtmlScrapeCapturer.createDefaultFilename_=function(a,b){return gdocs.Capturer.createFilenameFromTab(a,b?".html":"")};
gdocs.HtmlScrapeCapturer.prototype.startCapture=function(){this.callback_=goog.bind(this.onMessageCallback_,this);chrome.extension.onMessage.addListener(this.callback_);chrome.tabs.executeScript(this.getTab().id,{file:this.contentScript_})};
gdocs.HtmlScrapeCapturer.prototype.onMessageCallback_=function(a){chrome.extension.onMessage.removeListener(this.callback_);gdlog.info("HtmlScrapeCapturer.onHtmlCallback_","html length:"+a.length);var b=(new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,!this.getAllowConvert())).createFromHtml(a);b&&this.setFilename(b);a=this.createBlob(a);this.uploadBlob(a,gdocs.MIME_TYPE.HTML)};gdocs.ImageCapturer=function(a,b){gdocs.Capturer.call(this,a,b,gdocs.Capturer.createFilenameFromTab(b,".png"),!1);this.bg_=a;this.hasDisplayedDialog_=!1};goog.inherits(gdocs.ImageCapturer,gdocs.Capturer);gdocs.ImageCapturer.prototype.startCapture=function(){chrome.tabs.captureVisibleTab(chrome.windows.WINDOW_ID_CURRENT,{format:"png"},goog.bind(this.uploadImageUri,this))};
gdocs.ImageCapturer.prototype.uploadImageUri=function(a){this.displayDialog();if(a){var b=a.indexOf(",");a=a.substr(b+1);a=this.createDataUriBlob(a,!0);b=new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,!0);this.setFilename(b.createTitleFromText(this.getFilename(),gdocs.MIME_TYPE.PNG));this.uploadBlob(a,gdocs.MIME_TYPE.PNG)}else this.fatal(chrome.i18n.getMessage("IMAGE_CAPTURE_FAILED"))};
gdocs.ImageCapturer.prototype.displayDialog=function(){this.hasDisplayedDialog_||(this.bg_.displayWhenAuthorized(),this.hasDisplayedDialog_=!0)};gdocs.ImageEntireCapturer=function(a,b,c){gdocs.ImageCapturer.call(this,a,c);this.animatedBrowserIcon_=b;this.canvas_=document.createElement("canvas");this.columnNum_=this.rowNum_=this.visibleHeight_=this.visibleWidth_=0};goog.inherits(gdocs.ImageEntireCapturer,gdocs.ImageCapturer);gdocs.ImageEntireCapturer.EMPTY_URI_LENGTH_=6;
gdocs.ImageEntireCapturer.prototype.startCapture=function(){chrome.tabs.executeScript(this.getTab().id,{file:"js/contentscriptscroll.js"},goog.bind(this.initiateEntireCapture_,this));this.animatedBrowserIcon_.start()};gdocs.ImageEntireCapturer.prototype.initiateEntireCapture_=function(){this.sendMessage_({msg:"init"},goog.bind(this.processResponse_,this))};
gdocs.ImageEntireCapturer.prototype.processResponse_=function(a){if(a)switch(gdlog.fine("ImageEntireCapturer.processResponse","processResponse_:"+gdlog.prettyPrint(a)),a.msg){case "initialized":this.canvas_.width=a.bodyScrollWidth;this.canvas_.height=a.bodyScrollHeight;if(this.canvas_.toDataURL("image/png").length<=gdocs.ImageEntireCapturer.EMPTY_URI_LENGTH_){this.fatalCapture_(chrome.i18n.getMessage("PAGE_SIZE_NOT_SUPPORTED",this.canvas_.width+"x"+this.canvas_.height));break}this.visibleWidth_=a.visibleWidth;
this.visibleHeight_=a.visibleHeight;this.columnNum_=this.rowNum_=0;this.startStitch_();break;case "scrollToDone":this.startStitch_();break;case "endOfPage":a=this.canvas_.toDataURL("image/png"),this.animatedBrowserIcon_.stop(),this.uploadImageUri(a)}else gdlog.warn("ImageEntireCapturer.processResponse","No response. lastError:"+gdlog.prettyPrint(chrome.extension.lastError)),this.fatalLastError_()};
gdocs.ImageEntireCapturer.prototype.startStitch_=function(){chrome.tabs.update(this.getTab().id,{active:!0},goog.bind(this.captureVisibleAndContinue_,this))};gdocs.ImageEntireCapturer.prototype.captureVisibleAndContinue_=function(){chrome.tabs.captureVisibleTab(chrome.windows.WINDOW_ID_CURRENT,{format:"png"},goog.bind(this.stitchImageAndContinue_,this))};
gdocs.ImageEntireCapturer.prototype.stitchImageAndContinue_=function(a){if(a){var b=new Image;b.onload=goog.bind(this.handleImageOnLoad_,this);b.src=a}else gdlog.warn("ImageEntireCapturer.stitchImage","Capture failure dataUrl:"+a+" lastError:"+gdlog.prettyPrint(chrome.extension.lastError)),this.fatalLastError_()};
gdocs.ImageEntireCapturer.prototype.handleImageOnLoad_=function(a){a=a.target;var b=0,c=0,d=0,e=0,g=0,f=0;(this.columnNum_+1)*this.visibleWidth_>this.canvas_.width?(b=this.canvas_.width%this.visibleWidth_,d=(this.columnNum_+1)*this.visibleWidth_-this.canvas_.width):b=this.visibleWidth_;(this.rowNum_+1)*this.visibleHeight_>this.canvas_.height?(c=this.canvas_.height%this.visibleHeight_,e=(this.rowNum_+1)*this.visibleHeight_<this.canvas_.height?0:(this.rowNum_+1)*this.visibleHeight_-this.canvas_.height):
c=this.visibleHeight_;g=this.columnNum_*this.visibleWidth_;f=this.rowNum_*this.visibleHeight_;this.canvas_.getContext("2d").drawImage(a,d,e,b,c,g,f,b,c);gdlog.fine("ImageEntireCapturer.handleImageOnLoad","row:"+this.rowNum_+" column:"+this.columnNum_+" drawImage srcX:"+d+" srcY:"+e+" width:"+b+" height:"+c+" dstX:"+g+" dstY:"+f);this.columnNum_++;if(this.columnNum_*this.visibleWidth_>=this.canvas_.width&&(this.rowNum_++,this.columnNum_=0,this.rowNum_*this.visibleHeight_>=this.canvas_.height)){this.sendMessage_({msg:"restore"},
goog.bind(this.processResponse_,this));return}this.sendMessage_({msg:"scrollTo",x:this.columnNum_*this.visibleWidth_,y:this.rowNum_*this.visibleHeight_,capturePosition:this.getCornerPosition_()},goog.bind(this.processResponse_,this))};
gdocs.ImageEntireCapturer.prototype.getCornerPosition_=function(){var a=(this.columnNum_+1)*this.visibleWidth_>=this.canvas_.width,b=(this.rowNum_+1)*this.visibleHeight_>=this.canvas_.height;return 0==this.rowNum_&&a?"top_right":0==this.columnNum_&&b?"bottom_left":a&&b?"bottom_right":""};
gdocs.ImageEntireCapturer.prototype.sendMessage_=function(a,b){gdlog.fine("ImageEntireCapturer.sendMessage",gdlog.prettyPrint(a));chrome.tabs.sendMessage(this.getTab().id,a,b);chrome.extension.lastError&&(gdlog.warn("ImageEntireCapturer.sendMessage","chrome.tabs.sendMessage() failed. id:"+this.getTab().id+" lastError:"+gdlog.prettyPrint(chrome.extension.lastError)+"\nFailed sending message:\n"+gdlog.prettyPrint(a)),this.fatalLastError_())};
gdocs.ImageEntireCapturer.prototype.fatalCapture_=function(a){this.animatedBrowserIcon_.stop();this.fatal(a);this.displayDialog()};gdocs.ImageEntireCapturer.prototype.fatalLastError_=function(){chrome.extension.lastError&&chrome.extension.lastError.message?this.fatalCapture_(chrome.i18n.getMessage("IMAGE_CAPTURE_FAILED_REASON",chrome.extension.lastError.message)):this.fatalCapture_(chrome.i18n.getMessage("IMAGE_CAPTURE_FAILED"))};gdocs.Notify=function(a,b,c){this.notification_=window.webkitNotifications.createNotification(c||"images/driveicon32.png",b||"",a)};gdocs.Notify.prototype.show=function(){this.notification_.show()};gdocs.PageCapturer=function(a,b){gdocs.Capturer.call(this,a,b,chrome.i18n.getMessage("MHTML_DEFAULT_FILENAME"),!1)};goog.inherits(gdocs.PageCapturer,gdocs.Capturer);gdocs.PageCapturer.SUBJECT_=/Subject:\s*(.*)/;gdocs.PageCapturer.prototype.startCapture=function(){chrome.pageCapture.saveAsMHTML({tabId:this.getTab().id},goog.bind(this.pageCapturedAsMhtml_,this))};
gdocs.PageCapturer.prototype.pageCapturedAsMhtml_=function(a){if(chrome.extension.lastError)this.fatal(chrome.i18n.getMessage("FAILURE_PAGE_CAPTURE",String(chrome.extension.lastError)));else if(a){var b=new FileReader;b.onloadend=goog.bind(this.onLoadEnd_,this,a);b.readAsText(a)}else this.fatal(chrome.i18n.getMessage("EMPTY_PAGE_CAPTURE"))};
gdocs.PageCapturer.prototype.onLoadEnd_=function(a,b){if(b.target.readyState==FileReader.DONE){var c=this.getTab()?this.getTab().title:this.getFilename(),d=b.target.result.match(gdocs.PageCapturer.SUBJECT_);d&&(1<d.length&&d[1])&&(c=d[1]);(c=(new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,!this.getAllowConvert())).createTitleFromText(c,gdocs.MIME_TYPE.MHTML))&&this.setFilename(c);this.uploadBlob(a,gdocs.MIME_TYPE.MHTML)}};gdocs.BrowserAction=function(a){this.bg_=a;this.animatedBrowserIcon_=new gdocs.AnimatedBrowserIcon("images/driveicon19.png",new gdocs.AnimatedBrowserIconParams)};gdocs.BrowserAction.prototype.initialize=function(){chrome.browserAction.setTitle({title:chrome.i18n.getMessage("SAVE_TO_GOOGLE_DRIVE_ACTION")});chrome.browserAction.onClicked.addListener(goog.bind(this.browserActionHandler_,this))};
gdocs.BrowserAction.prototype.processTab_=function(a,b){var c=!1,d;switch(a){case gdocs.ACTION_ID.URL:d=gdocs.DownloadStarter.startUrlDownload(this.bg_,b.url,null,!1,gdocs.IMPRESSION.PAGE_ACTION_URL,chrome.i18n.getMessage("DEFAULT_FILENAME"),!0);break;case gdocs.ACTION_ID.HTML:case gdocs.ACTION_ID.HTML_DOC:d=a==gdocs.ACTION_ID.HTML;var e=new gdocs.HtmlScrapeCapturer(this.bg_,b,d);e.startCapture();d=new gdocs.CaptureUploadParams(e,d?gdocs.IMPRESSION.PAGE_ACTION_HTML:gdocs.IMPRESSION.PAGE_ACTION_DOC);
break;case gdocs.ACTION_ID.IMAGE_ENTIRE:d=new gdocs.ImageEntireCapturer(this.bg_,this.animatedBrowserIcon_,b);d.startCapture();c=!0;d=new gdocs.CaptureUploadParams(d,gdocs.IMPRESSION.PAGE_ACTION_CAPTURE_IMAGE_ENTIRE);break;case gdocs.ACTION_ID.IMAGE_VISIBLE:d=new gdocs.ImageCapturer(this.bg_,b);d.startCapture();c=!0;d=new gdocs.CaptureUploadParams(d,gdocs.IMPRESSION.PAGE_ACTION_CAPTURE_IMAGE_VISIBLE);break;case gdocs.ACTION_ID.MHTML:d=new gdocs.PageCapturer(this.bg_,b);d.startCapture();d=new gdocs.CaptureUploadParams(d,
gdocs.IMPRESSION.PAGE_ACTION_CAPTURE_MHTML);break;default:gdlog.warn("BrowserAction.processTabAction",'Unsupported feature: "'+a+'"');return}c?this.bg_.setUploadParams(d):this.bg_.initiateUploadToDrive(d)};gdocs.BrowserAction.prototype.browserActionHandler_=function(a){a&&(this.bg_.getTabContentType().isChromeInternalUrl(a)?(new gdocs.Notify(chrome.i18n.getMessage("CANNOT_CAPTURE_CHROME"))).show():this.processTab_(this.getDefaultActionId_(a),a))};
gdocs.BrowserAction.prototype.getDefaultActionId_=function(a){if(this.bg_.getTabContentType().isDataUri(a)||this.bg_.getTabContentType().isFileUrl(a))return gdocs.ACTION_ID.URL;if(this.bg_.getTabContentType().isCached(a))return this.bg_.getTabContentType().isDisplayingHtml(a)?this.bg_.getOptions().getHtmlFormat():gdocs.ACTION_ID.URL;gdlog.info("BrowserAction.getDefaultActionId","Tab is not cached; refresh required after extension is installed. Entire image capture instead.");return gdocs.ACTION_ID.IMAGE_ENTIRE};gdocs.Client=function(){this.oauth_=ChromeExOAuth.initBackgroundPage({request_url:"https://accounts.google.com/OAuthGetRequestToken",authorize_url:"https://accounts.google.com/OAuthAuthorizeToken",access_url:"https://accounts.google.com/OAuthGetAccessToken",consumer_key:"anonymous",consumer_secret:"anonymous",scope:"https://docs.google.com/feeds/",app_name:chrome.i18n.getMessage("CHROME_EXTENSION_NAME")})};goog.exportSymbol("gdocs.Client",gdocs.Client);
gdocs.Client.AuthState={AUTHENTICATED:"authenticated",AUTH_FAILED:"auth_failed"};gdocs.Client.prototype.isAuthorized=function(){return!!this.oauth_.hasToken()};gdocs.Client.prototype.oauthLogin=function(a){this.oauth_.authorize(goog.bind(this.oAuthAuthorizeCallback_,this,a))};gdocs.Client.prototype.oAuthAuthorizeCallback_=function(a,b){b||this.oauth_.clearTokens();a(b?gdocs.Client.AuthState.AUTHENTICATED:gdocs.Client.AuthState.AUTH_FAILED)};
gdocs.Client.prototype.sendRequest=function(a,b,c,d,e,g,f,i){if(i){c=this.encodeParams_(c);0<c.length&&(b=b+"?"+c);var h=new XMLHttpRequest;h.onreadystatechange=function(){4==h.readyState&&g(h)};h.open(a,b,!0);if(d)for(var j in d)h.setRequestHeader(j,d[j]);h.send(e)}else if(this.isAuthorized()){a={method:a,headers:d,body:e};c&&(a.parameters=c);try{this.oauth_.sendSignedRequest(b,goog.bind(this.oAuthCallback_,this,g,f,b),a)}catch(k){gdlog.warn("Client.sendRequest","Exception sending signed request:"+
gdlog.prettyPrint(a)+" to url:"+b+" e:"+k),f(k)}}else this.authFailCallback_(f,b)};gdocs.Client.prototype.oAuthCallback_=function(a,b,c,d,e){e.status==gdocs.HttpStatus.UNAUTHORIZED?(this.oauth_.clearTokens(),this.authFailCallback_(b,c)):a(e)};gdocs.Client.prototype.authFailCallback_=function(a,b){var c=chrome.i18n.getMessage("AUTH_URL_FAILURE",b);gdlog.warn("Client.sendRequest",c);a(Error(c))};gdocs.Client.prototype.logout=function(){this.oauth_.clearTokens()};
gdocs.Client.prototype.encodeParams_=function(a){if(!a)return"";var b=[],c=0,d;for(d in a)b[c++]=encodeURIComponent(d)+"="+encodeURIComponent(a[d]);return b.join("&")};gdocs.ContextMenu={};gdocs.ContextMenu.ContextType={PAGE:"page",LINK:"link",IMAGE:"image",VIDEO:"video",AUDIO:"audio"};gdocs.ContextMenu.createMenus=function(a){for(var b=[[gdocs.ContextMenu.ContextType.LINK,"SAVE_LINK"],[gdocs.ContextMenu.ContextType.IMAGE,"SAVE_IMAGE"],[gdocs.ContextMenu.ContextType.VIDEO,"SAVE_VIDEO"],[gdocs.ContextMenu.ContextType.AUDIO,"SAVE_AUDIO"]],c=0;c<b.length;c++){var d=b[c];gdocs.ContextMenu.createMenu_(d[1],d[0],gdocs.ContextMenu.createMenuClickCallback_(a))}};
gdocs.ContextMenu.createMenuClickCallback_=function(a){return function(b,c){var d=gdocs.ContextMenu.getUserImpression_(b),e=gdocs.ContextMenu.getClickUrl_(b),g=gdocs.ContextMenu.createDefaultFilenameFromMediaType_(b),d=gdocs.DownloadStarter.startUrlDownload(a,e,c.tabId,!0,d,g,!0);a.initiateUploadToDrive(d)}};
gdocs.ContextMenu.createMenu_=function(a,b,c){a=chrome.i18n.getMessage(a);c=chrome.contextMenus.create({title:a,contexts:[b],onclick:c});gdlog.info("ContextMenu.createMenu","created ContextMenu context:"+b+", returned id:"+c);return c};gdocs.ContextMenu.getClickUrl_=function(a){if(a.srcUrl)return a.srcUrl;if(a.linkUrl)return a.linkUrl;if(a.pageUrl)return a.pageUrl;if(a.frameUrl)return a.frameUrl;gdlog.warn("ContextMenu.getClickUrl","Unsupported info:"+gdlog.prettyPrint(a));return""};
gdocs.ContextMenu.getUserImpression_=function(a){if(!a.mediaType){if(a.linkUrl)return gdocs.IMPRESSION.LINK;gdlog.info("ContextMenu.getUserImpression","No mediaType nor linkUrl");return gdocs.IMPRESSION.OTHER}switch(a.mediaType){case "image":return gdocs.IMPRESSION.IMAGE;case "video":return gdocs.IMPRESSION.VIDEO;case "audio":return gdocs.IMPRESSION.AUDIO;default:return gdlog.info("ContextMenu.getUserImpression","Unsupported mediaType:"+a.mediaType),gdocs.IMPRESSION.OTHER}};
gdocs.ContextMenu.createDefaultFilenameFromMediaType_=function(a){return!a.mediaType?chrome.i18n.getMessage("DEFAULT_FILENAME"):gdocs.createBaseFilenameFromContentType(a.mediaType)};gdocs.BlobUploadParams=function(a,b,c,d,e){gdocs.UploadParams.call(this,c);this.blob_=a;this.allowConvert_=b;this.suggestedFilename_=d;this.contentType_=e||a.type};goog.inherits(gdocs.BlobUploadParams,gdocs.UploadParams);goog.exportSymbol("gdocs.BlobUploadParams",gdocs.BlobUploadParams);gdocs.BlobUploadParams.prototype.getBlob=function(){return this.blob_};goog.exportProperty(gdocs.BlobUploadParams.prototype,"getBlob",gdocs.BlobUploadParams.prototype.getBlob);
gdocs.BlobUploadParams.prototype.getAllowConvert=function(){return this.allowConvert_};goog.exportProperty(gdocs.BlobUploadParams.prototype,"getAllowConvert",gdocs.BlobUploadParams.prototype.getAllowConvert);gdocs.BlobUploadParams.prototype.getSuggestedFilename=function(){return this.suggestedFilename_};goog.exportProperty(gdocs.BlobUploadParams.prototype,"getSuggestedFilename",gdocs.BlobUploadParams.prototype.getSuggestedFilename);gdocs.BlobUploadParams.prototype.getContentType=function(){return this.contentType_};
goog.exportProperty(gdocs.BlobUploadParams.prototype,"getContentType",gdocs.BlobUploadParams.prototype.getContentType);gdocs.BlobUploadParams.prototype.isUploadOnly=function(){return!0};gdocs.IntentHandler=function(a){this.bg_=a};gdocs.IntentHandler.ACTION_SAVE_="http://webintents.org/save";gdocs.IntentHandler.prototype.handleIntent=function(a){gdlog.info("IntentHandler.handleIntent","handling intent "+a);a.action==gdocs.IntentHandler.ACTION_SAVE_&&this.handleSave_(a)};
gdocs.IntentHandler.prototype.handleSave_=function(a){var b=a.getExtra("filename"),c,d=a.type;b?(c=!1,b=b.toString()):(c=!0,b=d?gdocs.createBaseFilenameFromContentType(d):chrome.i18n.getMessage("DEFAULT_FILENAME"));var e=a.data;e?(this.uploadData_(e,d,b,c),a.postResult(null)):(d=a.getExtra("url"))?(this.uploadUrl_(d,b,c),a.postResult(null)):a.postFailure(null)};
gdocs.IntentHandler.prototype.uploadData_=function(a,b,c,d){"text/uri-list"==b&&goog.isString(a)?this.uploadUriList_(a,c,d):(a instanceof Blob||(a=new Blob([a],{type:b})),a=new gdocs.BlobUploadParams(a,!0,gdocs.IMPRESSION.DATA_WEB_INTENT,c,b),this.bg_.initiateUploadToDrive(a))};gdocs.IntentHandler.prototype.uploadUriList_=function(a,b,c){a=a.split("\r\n");for(var d=0;d<a.length;d++){var e=a[d].trim();if(e&&"#"!=e[0]){this.uploadUrl_(e,b,c);break}}};
gdocs.IntentHandler.prototype.uploadUrl_=function(a,b,c){a=gdocs.DownloadStarter.startUrlDownload(this.bg_,a,null,!0,gdocs.IMPRESSION.URL_WEB_INTENT,b,c);this.bg_.initiateUploadToDrive(a)};gdocs.Options=function(){};goog.exportSymbol("gdocs.Options",gdocs.Options);gdocs.Options.HTML_FORMAT_IDS=[gdocs.ACTION_ID.HTML_DOC,gdocs.ACTION_ID.IMAGE_ENTIRE,gdocs.ACTION_ID.IMAGE_VISIBLE,gdocs.ACTION_ID.HTML,gdocs.ACTION_ID.MHTML];gdocs.Options.HTML_FORMAT_KEY_="htmlFormat";gdocs.Options.CONVERT_TO_GOOGLE_FORMAT_KEY_="convertToGoogleFormat";gdocs.Options.prototype.getBooleanValue=function(a){return goog.isDef(window.localStorage[a])?"true"==window.localStorage[a]:this.getDefaultBooleanValue_(a)};
gdocs.Options.prototype.getDefaultBooleanValue_=function(){return!1};gdocs.Options.prototype.setBooleanValue=function(a,b){window.localStorage[a]=String(b)};gdocs.Options.prototype.getHtmlFormat=function(){var a=window.localStorage[gdocs.Options.HTML_FORMAT_KEY_];return a?a:gdocs.ACTION_ID.IMAGE_ENTIRE};gdocs.Options.prototype.setHtmlFormat=function(a){window.localStorage[gdocs.Options.HTML_FORMAT_KEY_]=String(a)};goog.exportProperty(gdocs.Options.prototype,"setHtmlFormat",gdocs.Options.prototype.setHtmlFormat);
gdocs.Options.prototype.getConvertToGoogleFormat=function(){var a=gdocs.Options.CONVERT_TO_GOOGLE_FORMAT_KEY_;return goog.isDef(window.localStorage[a])?"true"==window.localStorage[a]:!1};gdocs.Options.prototype.setConvertToGoogleFormat=function(a){window.localStorage[gdocs.Options.CONVERT_TO_GOOGLE_FORMAT_KEY_]=String(a)};goog.exportProperty(gdocs.Options.prototype,"setConvertToGoogleFormat",gdocs.Options.prototype.setConvertToGoogleFormat);gdocs.TabContentType=function(){this.tabContentType_={};chrome.tabs.onRemoved.addListener(goog.bind(this.removedCallback_,this));chrome.webRequest.onResponseStarted.addListener(goog.bind(this.responseStartedCallback_,this),{urls:["<all_urls>"],types:["main_frame"]},["responseHeaders"])};gdocs.TabContentType.prototype.isCached=function(a){var b=a.id;return!this.tabContentType_[b]?(gdlog.warn("TabContentType.isCached","No cached contentType for tabId:"+b+" ("+a.title+"). Refresh tab"),!1):!0};
gdocs.TabContentType.prototype.isChromeInternalUrl=function(a){return 0==a.url.indexOf("chrome://")||0==a.url.indexOf("chrome-devtools://")||0==a.url.indexOf("chrome-extension://")||0==a.url.indexOf("about:")||0==a.url.indexOf("view-source:")||0==a.url.indexOf("https://chrome.google.com/webstore/")};gdocs.TabContentType.prototype.isFileUrl=function(a){return 0==a.url.indexOf("file://")};gdocs.TabContentType.prototype.isDataUri=function(a){return 0==a.url.indexOf("data:")};
gdocs.TabContentType.prototype.isDisplayingHtml=function(a){return 0==this.tabContentType_[a.id].indexOf("text/html")};gdocs.TabContentType.prototype.getContentType=function(a){return this.tabContentType_[a.id]};gdocs.TabContentType.prototype.removedCallback_=function(a){this.tabContentType_[a]&&delete this.tabContentType_[a]};
gdocs.TabContentType.prototype.responseStartedCallback_=function(a){var b=a.responseHeaders;if(b){for(var c,d=0;d<b.length;d++){var e=b[d];if("content-type"==e.name.toLowerCase()){c=e.value;break}}c&&(a=a.tabId)&&(this.tabContentType_[a]=c.toLowerCase())}};gdocs.DocList=function(a){this.client_=a};gdocs.DocList.Feed={METADATA:gdocs.GOOGLE_DOCS_ROOT_URL+"feeds/metadata/default",UPLOAD_RESUMABLE:gdocs.GOOGLE_DOCS_ROOT_URL+"feeds/upload/create-session/default/private/full/"};gdocs.DocList.addHeaders=function(a){a=a||{};a["GData-Version"]="3.0";a["X-User-Agent"]="google-docschromeextension-1.5";return a};
gdocs.DocList.prototype.loadMetadata=function(a,b){var c=gdocs.DocList.addHeaders();this.getFeed_(gdocs.DocList.Feed.METADATA,c,goog.bind(this.handleMetadataResults_,this,a,b),b)};gdocs.DocList.prototype.handleMetadataResults_=function(a,b,c){c.entry?a(c.entry.author[0].email.$t):b(chrome.i18n.getMessage("USER_INFO_FAILURE"))};
gdocs.DocList.prototype.renameFile=function(a,b,c,d){a=gdocs.DocList.createTitleBody(a);var e=gdocs.DocList.addHeaders({"Content-Type":gdocs.MIME_TYPE.ATOM,"If-Match":"*"});this.putAtomFeed_(b,e,a,goog.bind(this.handleRenameResults_,this,c,d),d)};gdocs.DocList.createTitleBody=function(a){return"<?xml version='1.0' encoding='UTF-8'?>\n<entry xmlns=\"http://www.w3.org/2005/Atom\">\n<title>"+gdocs.xmlEncode(a)+"</title>\n</entry>"};gdocs.DocList.prototype.handleRenameResults_=function(a){a()};
gdocs.DocList.prototype.trashFile=function(a,b,c){var d=gdocs.DocList.addHeaders({"Content-Type":gdocs.MIME_TYPE.ATOM,"If-Match":"*"});this.deleteAtomFeed_(a,d,null,goog.bind(this.handleTrashResults_,this,b),c)};gdocs.DocList.prototype.handleTrashResults_=function(a){a()};gdocs.DocList.prototype.getFeed_=function(a,b,c,d){this.client_.sendRequest("GET",a,{alt:"json"},b,null,goog.bind(this.handleFeedSuccess_,this,c,d),goog.bind(this.handleFeedException_,this,d))};
gdocs.DocList.prototype.putAtomFeed_=function(a,b,c,d,e){this.client_.sendRequest("PUT",a,{alt:"json"},b,c,goog.bind(this.handleFeedSuccess_,this,d,e),goog.bind(this.handleFeedException_,this,e))};gdocs.DocList.prototype.handleFeedSuccess_=function(a,b,c){if(200<=c.status&&202>=c.status){var d=JSON.parse(c.responseText);d?a(d):(a=chrome.i18n.getMessage("DOCS_API_FAILURE",gdocs.createXhrErrMsg(c)),gdlog.warn("DocList.handleFeedSuccess","errMsg:"+a+" responseText:"+c.responseText),b(Error(a)))}else b(Error(gdocs.createXhrErrMsg(c)))};
gdocs.DocList.prototype.handleFeedException_=function(a,b){a(b)};gdocs.DocList.prototype.deleteAtomFeed_=function(a,b,c,d,e){this.client_.sendRequest("DELETE",a,{alt:"json"},b,c,goog.bind(this.handleDeleteSuccess_,this,d,e),goog.bind(this.handleFeedException_,this,e))};gdocs.DocList.prototype.handleDeleteSuccess_=function(a,b,c){200<=c.status&&202>=c.status?a():b(gdocs.createXhrErrMsg(c))};gdocs.UserId=function(a){this.client_=a;this.docList_=new gdocs.DocList(a);this.currentId_="";this.seenGoogle_=!1};goog.exportSymbol("gdocs.UserId",gdocs.UserId);gdocs.UserId.GOOGLE_LC_SUFFIX_="@google.com";gdocs.UserId.prototype.getUserIdStr=function(a){this.client_.isAuthorized()?this.currentId_?a(this.currentId_):this.docList_.loadMetadata(goog.bind(this.metadataCallback_,this,a),goog.bind(this.metadataFailure_,this,a)):(this.currentId_="",a(this.currentId_))};
goog.exportProperty(gdocs.UserId.prototype,"getUserIdStr",gdocs.UserId.prototype.getUserIdStr);gdocs.UserId.prototype.metadataCallback_=function(a,b){this.endsWith_(b,gdocs.UserId.GOOGLE_LC_SUFFIX_)&&(this.seenGoogle_=!0);this.currentId_=b;a(this.currentId_)};gdocs.UserId.prototype.metadataFailure_=function(a,b){gdlog.warn("UserId","Failure accessing metadata:"+b);this.currentId_="";a(this.currentId_)};gdocs.UserId.prototype.invalidate=function(){this.currentId_=""};
gdocs.UserId.prototype.isGoogle=function(){return this.seenGoogle_};goog.exportProperty(gdocs.UserId.prototype,"isGoogle",gdocs.UserId.prototype.isGoogle);gdocs.UserId.prototype.endsWith_=function(a,b){var c=a.length-b.length;return 0>c?!1:-1!=a.toLowerCase().indexOf(b,c)};gdocs.BackgroundPage=function(){this.client_=new gdocs.Client;this.uploadParams_=null;this.tabContentType_=new gdocs.TabContentType;this.options_=new gdocs.Options;this.browserAction_=new gdocs.BrowserAction(this);this.browserAction_.initialize();this.intentHandler_=new gdocs.IntentHandler(this);this.userId_=new gdocs.UserId(this.client_);gdocs.ContextMenu.createMenus(this)};goog.exportSymbol("gdocs.BackgroundPage",gdocs.BackgroundPage);gdocs.BackgroundPage.UPLOAD_DIALOG_INNER_WIDTH_=417;
gdocs.BackgroundPage.UPLOAD_DIALOG_INNER_HEIGHT_=170;gdocs.BackgroundPage.prototype.getTabContentType=function(){return this.tabContentType_};gdocs.BackgroundPage.prototype.getUploadParams=function(){if(!this.uploadParams_)throw"uploadParams not set";return this.uploadParams_};goog.exportProperty(gdocs.BackgroundPage.prototype,"getUploadParams",gdocs.BackgroundPage.prototype.getUploadParams);gdocs.BackgroundPage.prototype.getClient=function(){return this.client_};
goog.exportProperty(gdocs.BackgroundPage.prototype,"getClient",gdocs.BackgroundPage.prototype.getClient);gdocs.BackgroundPage.prototype.getOptions=function(){return this.options_};goog.exportProperty(gdocs.BackgroundPage.prototype,"getOptions",gdocs.BackgroundPage.prototype.getOptions);gdocs.BackgroundPage.prototype.getIntentHandler=function(){return this.intentHandler_};goog.exportProperty(gdocs.BackgroundPage.prototype,"getIntentHandler",gdocs.BackgroundPage.prototype.getIntentHandler);
gdocs.BackgroundPage.prototype.getLogLevel=function(){return gdlog.loglevel};goog.exportProperty(gdocs.BackgroundPage.prototype,"getLogLevel",gdocs.BackgroundPage.prototype.getLogLevel);
gdocs.BackgroundPage.prototype.showUploadDialog_=function(){var a=gdocs.BackgroundPage.UPLOAD_DIALOG_INNER_WIDTH_,b=gdocs.BackgroundPage.UPLOAD_DIALOG_INNER_HEIGHT_;0==navigator.platform.indexOf("Win")?(a+=5,b+=40):0<=navigator.userAgent.indexOf(" CrOS ")&&(a+=5,b+=24);gdlog.info("BackgroundPage.showUploadDialog","Creating popup window "+a+"x"+b);chrome.windows.create({url:chrome.extension.getURL("upload.html"),type:"popup",width:a,height:b})};
gdocs.BackgroundPage.prototype.initiateUploadToDrive=function(a){gdlog.info("BackgroundPage.initiateUploadToDrive","impression:"+a.getUserImpression());this.setUploadParams(a);this.displayWhenAuthorized()};gdocs.BackgroundPage.prototype.setUploadParams=function(a){this.uploadParams_=a};gdocs.BackgroundPage.prototype.displayWhenAuthorized=function(){this.client_.isAuthorized()?this.showUploadDialog_():this.client_.oauthLogin(goog.bind(this.createSaveToAuthCallback_,this))};
gdocs.BackgroundPage.prototype.createSaveToAuthCallback_=function(a){a==gdocs.Client.AuthState.AUTHENTICATED?this.showUploadDialog_():gdlog.warn("BackgroundPage.createSaveToAuthCallback","Not authorized")};gdocs.BackgroundPage.prototype.getUserId=function(){return this.userId_};goog.exportProperty(gdocs.BackgroundPage.prototype,"getUserId",gdocs.BackgroundPage.prototype.getUserId);gdocs.BackgroundPage.prototype.logout=function(){this.userId_.invalidate();this.client_.logout()};
goog.exportProperty(gdocs.BackgroundPage.prototype,"logout",gdocs.BackgroundPage.prototype.logout);window.addEventListener("load",function(){chrome.extension.getBackgroundPage().bg=new gdocs.BackgroundPage},!1);
