var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};
goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,g=0;d=b[g];g++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.useStrictRequires=!1;goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);if(goog.useStrictRequires)throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=
-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(!goog.isProvided_(f))if(f in d.nameToPath)a(d.nameToPath[f]);else throw Error("Undefined nameToPath for "+f);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){goog.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.getMsgWithFallback=function(a){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===d)g=!0;else if(g)return f.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};goog.MODIFY_FUNCTION_PROTOTYPES=!0;
goog.MODIFY_FUNCTION_PROTOTYPES&&(Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return goog.bind.apply(null,c)}return goog.bind(this,a)},Function.prototype.partial=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return goog.bind.apply(null,b)},Function.prototype.inherits=function(a){goog.inherits(this,a)},Function.prototype.mixin=function(a){goog.mixin(this.prototype,
a)});var gdocs={domUtil:{}};gdocs.domUtil.HIDDEN_CLASS_="gdocs-hidden";gdocs.domUtil.getHtmlElementByIdAssert=function(a){var b=document.getElementById(a);if(!b)throw'Could not find Element with id: "'+a+'"';return b};gdocs.domUtil.setTextContent=function(a,b){a.textContent=b};gdocs.domUtil.setTextContentId=function(a,b){var c=document.getElementById(a);c&&gdocs.domUtil.setTextContent(c,b)};gdocs.domUtil.hideElem=function(a){for(var b=0;b<arguments.length;b++)arguments[b].classList.add(gdocs.domUtil.HIDDEN_CLASS_)};
gdocs.domUtil.showElem=function(a){for(var b=0;b<arguments.length;b++)arguments[b].classList.remove(gdocs.domUtil.HIDDEN_CLASS_)};gdocs.GOOGLE_DOCS_ROOT_URL="https://docs.google.com/";gdocs.IMPRESSION={OTHER:0,LINK:2,IMAGE:3,AUDIO:4,VIDEO:5,PAGE_ACTION_URL:6,PAGE_ACTION_DOC:7,PAGE_ACTION_HTML:8,PAGE_ACTION_CAPTURE_IMAGE_VISIBLE:9,PAGE_ACTION_CAPTURE_MHTML:10,DATA_WEB_INTENT:13,URL_WEB_INTENT:14,PAGE_ACTION_CAPTURE_IMAGE_ENTIRE:15};gdocs.HttpStatus={OK:200,CREATED:201,ACCEPTED:202,RESUME_INCOMPLETE:308,UNAUTHORIZED:401};gdocs.IMPRESSION_HEADER="X-DocsExt-Action";
gdocs.impressionHeader=function(a,b){var c=b||{};c[gdocs.IMPRESSION_HEADER]=a.toString();return c};gdocs.MAX_GENERATED_TITLE_LEN=50;gdocs.MAX_SUFFIX_LEN=8;gdocs.UPLOAD_CHUNK_SIZE=262144;gdocs.KEYCODE_ESCAPE="27";gdocs.MIME_TYPE={ATOM:"application/atom+xml",HTML:"text/html",MHTML:"text/mhtml",OCTET_STREAM:"application/octet-stream",PLAIN:"text/plain",PDF:"application/pdf",PNG:"image/png",X_PDF:"application/x-pdf",XML:"text/xml"};
gdocs.EXTENSIONS={"application/msword":"doc","application/pdf":"pdf","application/rtf":"rtf","application/vnd.ms-excel":"xls","application/vnd.ms-powerpoint":"ppt","application/vnd.openxmlformats-officedocument.presentationml.presentation":"pptx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"xlsx","application/vnd.openxmlformats-officedocument.wordprocessingml.document":".docx","application/x-gzip":"gzip","application/x-pdf":"pdf","application/zip":"zip","audio/mp4":"mp4","audio/mpeg":"mp3",
"audio/ogg":"ogg","audio/vnd.wave":"wav","image/gif":"gif","image/jpeg":"jpg","image/pjpeg":"jpg","image/png":"png","image/svg+xml":"svg","image/tiff":"tif","image/vnd.microsoft.icon":"ico","text/css":"css","text/csv":"csv","text/html":"html","text/mhtml":"mht","text/plain":"txt","text/tsv":"tsv","text/xml":"xml","video/mp4":"mp4","video/mpeg":"mpg","video/ogg":"ogg"};
gdocs.CONVERTIBLE={"application/msword":!0,"application/rtf":!0,"application/vnd.ms-excel":!0,"application/vnd.ms-powerpoint":!0,"application/vnd.openxmlformats-officedocument.presentationml.presentation":!0,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":!0,"application/vnd.openxmlformats-officedocument.wordprocessingml.document":!0,"text/csv":!0,"text/html":!0,"text/plain":!0,"text/tsv":!0};
gdocs.ACTION_ID={BUG_INTERNAL:"bug-internal",FEEDBACK_INTERNAL:"feedback-internal",HELP:"help",HTML:"html",HTML_DOC:"htmldoc",IMAGE_ENTIRE:"image-entire",IMAGE_VISIBLE:"image-visible",MHTML:"mhtml",OPTIONS:"options",SEND_FEEDBACK:"send-feedback",URL:"url"};gdocs.createXhrErrMsg=function(a){var b=a.statusText;b||(b=chrome.i18n.getMessage("UNSPECIFIED_ERROR"));a.status&&(b+=" ("+a.status+")");return b};
gdocs.xmlEncode=function(a){return a.replace(/\&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\'/g,"&apos;").replace(/\"/g,"&quot;")};gdocs.createBaseFilenameFromContentType=function(a){a=a.toLowerCase();return 0==a.indexOf("image")?chrome.i18n.getMessage("IMAGE_DEFAULT_FILENAME"):0==a.indexOf("video")?chrome.i18n.getMessage("VIDEO_DEFAULT_FILENAME"):0==a.indexOf("audio")?chrome.i18n.getMessage("AUDIO_DEFAULT_FILENAME"):chrome.i18n.getMessage("DEFAULT_FILENAME")};gdocs.UrlUtil={};gdocs.UrlUtil.executeUrl=function(a){chrome.windows.create({url:gdocs.UrlUtil.createUrl_(a),type:"normal"})};gdocs.UrlUtil.createUrl_=function(a){return a==gdocs.ACTION_ID.BUG_INTERNAL||a==gdocs.ACTION_ID.FEEDBACK_INTERNAL?gdocs.UrlUtil.createInternalGotoUrl_(a):a==gdocs.ACTION_ID.SEND_FEEDBACK?gdocs.UrlUtil.createExternalFeedbackUrl_():gdocs.UrlUtil.createExternalHelpUrl_()};
gdocs.UrlUtil.createInternalGotoUrl_=function(a){return a==gdocs.ACTION_ID.BUG_INTERNAL?"http://goto.ext.google.com/drive-extension-bug?foundIn="+chrome.app.getDetails().version:"http://goto.ext.google.com/drive-extension-feedback"};gdocs.UrlUtil.createExternalFeedbackUrl_=function(){var a="https://chrome.google.com/webstore/support/"+chrome.i18n.getMessage("@@extension_id"),b=chrome.i18n.getMessage("@@ui_locale");b&&(a+="?hl="+b);return a+"#bug"};
gdocs.UrlUtil.createExternalHelpUrl_=function(){var a="http://support.google.com/drive/?",b=chrome.i18n.getMessage("@@ui_locale");b&&(a+="hl="+b+"&");return a+"p=extension_help"};gdocs.OptionsPage=function(a){this.bg_=a;this.convertEl_=gdocs.domUtil.getHtmlElementByIdAssert("convert");this.signOutEl_=gdocs.domUtil.getHtmlElementByIdAssert("sign-out");this.shownGoogleInternal_=!1;gdocs.domUtil.setTextContentId("title",chrome.i18n.getMessage("OPTIONS_TITLE"));gdocs.domUtil.setTextContentId("header-text",chrome.i18n.getMessage("OPTIONS_HEADER_TEXT"));gdocs.domUtil.setTextContentId("account",chrome.i18n.getMessage("ACCOUNT"));gdocs.domUtil.setTextContentId("sign-out",chrome.i18n.getMessage("SIGN_OUT"));
gdocs.domUtil.setTextContentId("save-as-text",chrome.i18n.getMessage("SAVE_PAGE_AS"));gdocs.domUtil.setTextContentId("save-image-entire",chrome.i18n.getMessage("SAVE_AS_IMAGE_ENTIRE"));gdocs.domUtil.setTextContentId("save-image-visible",chrome.i18n.getMessage("SAVE_AS_IMAGE_VISIBLE"));gdocs.domUtil.setTextContentId("save-html",chrome.i18n.getMessage("SAVE_AS_HTML"));gdocs.domUtil.setTextContentId("save-mhtml",chrome.i18n.getMessage("SAVE_AS_MHTML"));gdocs.domUtil.setTextContentId("save-htmldoc",chrome.i18n.getMessage("SAVE_AS_HTMLDOC"));
gdocs.domUtil.setTextContentId("misc-text",chrome.i18n.getMessage("MISC"));gdocs.domUtil.setTextContentId("convert-to-docs",chrome.i18n.getMessage("CONVERT_TO_GOOGLE_FORMAT"));gdocs.domUtil.setTextContentId("debug-text",chrome.i18n.getMessage("DEBUG"));gdocs.domUtil.setTextContentId("privacy-link",chrome.i18n.getMessage("PRIVACY"))};
gdocs.OptionsPage.prototype.populate=function(){this.bg_.getClient().isAuthorized()?(this.bg_.getUserId().getUserIdStr(goog.bind(this.setUserId_,this)),this.signOutEl_.addEventListener("click",goog.bind(this.handleRevoke_,this),!1)):this.disableSignout_();for(var a=this.bg_.getOptions().getHtmlFormat(),b=document.getElementsByName("html-format"),c=0;c<b.length;c++){var d=b[c];d.checked=d.id==a;d.addEventListener("click",goog.bind(this.handleRadio_,this),!1)}this.convertEl_.checked=this.bg_.getOptions().getConvertToGoogleFormat();
this.convertEl_.addEventListener("click",goog.bind(this.handleConvert_,this),!1);this.attachUrlActionMsg_("send-feedback","SEND_FEEDBACK");this.attachUrlActionMsg_("help","HELP");this.checkGoogle_()};gdocs.OptionsPage.prototype.setUserId_=function(a){gdocs.domUtil.setTextContentId("user-id",a);this.checkGoogle_()};
gdocs.OptionsPage.prototype.attachUrlActionMsg_=function(a,b){var c=gdocs.domUtil.getHtmlElementByIdAssert(a);gdocs.domUtil.setTextContent(c,chrome.i18n.getMessage(b));c.addEventListener("click",goog.bind(gdocs.UrlUtil.executeUrl,this,a),!1)};gdocs.OptionsPage.prototype.handleRadio_=function(a){a=a.currentTarget.id;this.bg_.getOptions().setHtmlFormat(a)};gdocs.OptionsPage.prototype.handleConvert_=function(a){this.bg_.getOptions().setConvertToGoogleFormat(a.currentTarget.checked)};
gdocs.OptionsPage.prototype.handleRevoke_=function(){this.disableSignout_();this.bg_.logout()};gdocs.OptionsPage.prototype.disableSignout_=function(){this.setUserId_("");this.signOutEl_.disabled="DISABLED"};
gdocs.OptionsPage.prototype.checkGoogle_=function(){!this.shownGoogleInternal_&&this.bg_.getUserId().isGoogle()&&(gdocs.domUtil.showElem(gdocs.domUtil.getHtmlElementByIdAssert("internal")),this.attachUrlActionMsg_("feedback-internal","FEEDBACK_INTERNAL"),this.attachUrlActionMsg_("bug-internal","FILE_BUG_INTERNAL"),this.shownGoogleInternal_=!0)};window.addEventListener("load",function(){var a=chrome.extension.getBackgroundPage().bg;(new gdocs.OptionsPage(a)).populate()},!1);
