var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};
goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,f=0;d=b[f];f++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.useStrictRequires=!1;goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);if(goog.useStrictRequires)throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=
-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var g in d.requires[e])if(!goog.isProvided_(g))if(g in d.nameToPath)a(d.nameToPath[g]);else throw Error("Undefined nameToPath for "+g);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){goog.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.getMsgWithFallback=function(a){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),f=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)f=!0;else if(f)return g.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};goog.MODIFY_FUNCTION_PROTOTYPES=!0;
goog.MODIFY_FUNCTION_PROTOTYPES&&(Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return goog.bind.apply(null,c)}return goog.bind(this,a)},Function.prototype.partial=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return goog.bind.apply(null,b)},Function.prototype.inherits=function(a){goog.inherits(this,a)},Function.prototype.mixin=function(a){goog.mixin(this.prototype,
a)});var gdocs={DataSource:function(){}};gdocs.DataSource.prototype.startWhenReady=function(a){a.startResumableUpload()};gdocs.GOOGLE_DOCS_ROOT_URL="https://docs.google.com/";gdocs.IMPRESSION={OTHER:0,LINK:2,IMAGE:3,AUDIO:4,VIDEO:5,PAGE_ACTION_URL:6,PAGE_ACTION_DOC:7,PAGE_ACTION_HTML:8,PAGE_ACTION_CAPTURE_IMAGE_VISIBLE:9,PAGE_ACTION_CAPTURE_MHTML:10,DATA_WEB_INTENT:13,URL_WEB_INTENT:14,PAGE_ACTION_CAPTURE_IMAGE_ENTIRE:15};gdocs.HttpStatus={OK:200,CREATED:201,ACCEPTED:202,RESUME_INCOMPLETE:308,UNAUTHORIZED:401};gdocs.IMPRESSION_HEADER="X-DocsExt-Action";
gdocs.impressionHeader=function(a,b){var c=b||{};c[gdocs.IMPRESSION_HEADER]=a.toString();return c};gdocs.MAX_GENERATED_TITLE_LEN=50;gdocs.MAX_SUFFIX_LEN=8;gdocs.UPLOAD_CHUNK_SIZE=262144;gdocs.KEYCODE_ESCAPE="27";gdocs.MIME_TYPE={ATOM:"application/atom+xml",HTML:"text/html",MHTML:"text/mhtml",OCTET_STREAM:"application/octet-stream",PLAIN:"text/plain",PDF:"application/pdf",PNG:"image/png",X_PDF:"application/x-pdf",XML:"text/xml"};
gdocs.EXTENSIONS={"application/msword":"doc","application/pdf":"pdf","application/rtf":"rtf","application/vnd.ms-excel":"xls","application/vnd.ms-powerpoint":"ppt","application/vnd.openxmlformats-officedocument.presentationml.presentation":"pptx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"xlsx","application/vnd.openxmlformats-officedocument.wordprocessingml.document":".docx","application/x-gzip":"gzip","application/x-pdf":"pdf","application/zip":"zip","audio/mp4":"mp4","audio/mpeg":"mp3",
"audio/ogg":"ogg","audio/vnd.wave":"wav","image/gif":"gif","image/jpeg":"jpg","image/pjpeg":"jpg","image/png":"png","image/svg+xml":"svg","image/tiff":"tif","image/vnd.microsoft.icon":"ico","text/css":"css","text/csv":"csv","text/html":"html","text/mhtml":"mht","text/plain":"txt","text/tsv":"tsv","text/xml":"xml","video/mp4":"mp4","video/mpeg":"mpg","video/ogg":"ogg"};
gdocs.CONVERTIBLE={"application/msword":!0,"application/rtf":!0,"application/vnd.ms-excel":!0,"application/vnd.ms-powerpoint":!0,"application/vnd.openxmlformats-officedocument.presentationml.presentation":!0,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":!0,"application/vnd.openxmlformats-officedocument.wordprocessingml.document":!0,"text/csv":!0,"text/html":!0,"text/plain":!0,"text/tsv":!0};
gdocs.ACTION_ID={BUG_INTERNAL:"bug-internal",FEEDBACK_INTERNAL:"feedback-internal",HELP:"help",HTML:"html",HTML_DOC:"htmldoc",IMAGE_ENTIRE:"image-entire",IMAGE_VISIBLE:"image-visible",MHTML:"mhtml",OPTIONS:"options",SEND_FEEDBACK:"send-feedback",URL:"url"};gdocs.createXhrErrMsg=function(a){var b=a.statusText;b||(b=chrome.i18n.getMessage("UNSPECIFIED_ERROR"));a.status&&(b+=" ("+a.status+")");return b};
gdocs.xmlEncode=function(a){return a.replace(/\&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\'/g,"&apos;").replace(/\"/g,"&quot;")};gdocs.createBaseFilenameFromContentType=function(a){a=a.toLowerCase();return 0==a.indexOf("image")?chrome.i18n.getMessage("IMAGE_DEFAULT_FILENAME"):0==a.indexOf("video")?chrome.i18n.getMessage("VIDEO_DEFAULT_FILENAME"):0==a.indexOf("audio")?chrome.i18n.getMessage("AUDIO_DEFAULT_FILENAME"):chrome.i18n.getMessage("DEFAULT_FILENAME")};gdocs.BlobDataSource=function(a,b,c,d){gdocs.DataSource.call(this);this.blob_=a;this.allowConvert_=b;this.filename_=c;this.contentType_=d.toLowerCase()};goog.inherits(gdocs.BlobDataSource,gdocs.DataSource);gdocs.BlobDataSource.prototype.getDriveFilename=function(){return this.filename_};gdocs.BlobDataSource.prototype.getContentType=function(){return this.contentType_};gdocs.BlobDataSource.prototype.shouldConvert=function(){return this.allowConvert_&&this.getContentType()in gdocs.CONVERTIBLE};
gdocs.BlobDataSource.prototype.getSize=function(){return this.blob_.size};gdocs.BlobDataSource.prototype.getData=function(a,b){return this.blob_.slice(a,b)};var gdlog={};goog.exportSymbol("gdlog",gdlog);gdlog.Level={SEVERE:1E3,WARNING:900,INFO:800,CONFIG:700,FINE:500,FINER:400,FINEST:300};gdlog.ENABLE_DEBUG_FLAG=!0;gdlog.DEFAULT_LEVEL_UNCOMPILED_=gdlog.Level.INFO;gdlog.DEFAULT_LEVEL_COMPILED_=gdlog.Level.WARNING;gdlog.loglevel=gdlog.ENABLE_DEBUG_FLAG?gdlog.DEFAULT_LEVEL_UNCOMPILED_:gdlog.DEFAULT_LEVEL_COMPILED_;goog.exportSymbol("gdlog.loglevel",gdlog.loglevel);gdlog.msg_=function(a,b){return a+": "+b};gdlog.isLoggable_=function(a){return a>=gdlog.loglevel};
gdlog.error=function(a,b){window.console.error(gdlog.msg_(a,b))};gdlog.warn=function(a,b){gdlog.isLoggable_(gdlog.Level.WARNING)&&window.console.warn(gdlog.msg_(a,b))};gdlog.info=function(a,b){gdlog.isLoggable_(gdlog.Level.INFO)&&window.console.info(gdlog.msg_(a,b))};gdlog.fine=function(a,b){gdlog.isLoggable_(gdlog.Level.FINE)&&window.console.log(gdlog.msg_(a,b))};gdlog.finer=function(a,b){gdlog.isLoggable_(gdlog.Level.FINER)&&window.console.debug(gdlog.msg_(a,b))};
gdlog.logwarn=function(){return gdlog.setLoggingLevel_(gdlog.Level.WARNING,"WARN")};goog.exportSymbol("gdlog.logwarn",gdlog.logwarn);gdlog.loginfo=function(){return gdlog.setLoggingLevel_(gdlog.Level.INFO,"INFO")};goog.exportSymbol("gdlog.loginfo",gdlog.loginfo);gdlog.logfine=function(){return gdlog.setLoggingLevel_(gdlog.Level.FINE,"FINE")};goog.exportSymbol("gdlog.logfine",gdlog.logfine);gdlog.logfiner=function(){return gdlog.setLoggingLevel_(gdlog.Level.FINER,"FINER")};
goog.exportSymbol("gdlog.logfiner",gdlog.logfiner);gdlog.setLoggingLevel_=function(a,b){gdlog.loglevel=a;return"Log level is now "+b};gdlog.prettyPrint=function(a,b){if(!a)return'""';var c=b||100,d={},e;for(e in a){var f=String(a[e]),g=f.length;g>c&&(f=f.substr(0,c)+" ... ("+g+" bytes)");d[e]=f}return JSON.stringify(d,null,2)};gdocs.TitleComputer=function(a,b,c){if(0>=a)throw Error("Maximum title length must be > 0");if(0>b)throw Error("Maximum suffix length must be >= 0");if(b>=a)throw Error("Maximum suffix length must be less than Maximum title length");this.maxTitleLen_=a;this.maxSuffixLen_=b;this.addExtension_=c};gdocs.TitleComputer.TRIM_=/^\s+|\s+$/g;gdocs.TitleComputer.COLLAPSE_SPACES_=/\s+/g;gdocs.TitleComputer.STRIP_META_=/<meta[^>]+>/img;gdocs.TitleComputer.TITLE_CONTENTS_=/<title>\s*([\s\S]+?)\s*<\/title/im;
gdocs.TitleComputer.prototype.createTitleFromText=function(a,b){var c=this.unescapeHtml_(a);if(!c)return null;c=c.replace(gdocs.TitleComputer.COLLAPSE_SPACES_," ");c=c.replace(gdocs.TitleComputer.TRIM_,"");if(!c.length)return null;var c=this.appendContentTypeExtension_(c,b),d="";if(c.length>this.maxTitleLen_){var e=this.splitExtension_(c),f=this.maxTitleLen_;e[1]&&(c=e[0],d="."+e[1],f-=d.length);c=c.substr(0,f);e=Math.max(c.lastIndexOf(" "),c.lastIndexOf("-"),c.lastIndexOf("_"));0<e&&(e=c.substr(0,
e),0<e.length&&(c=e))}return c+d};gdocs.TitleComputer.prototype.splitExtension_=function(a){var b=a.lastIndexOf(".");if(0<b&&b+1!=a.length&&a.length-b-1<=this.maxSuffixLen_){var c=a.substr(b+1);return[a.substr(0,b),c]}return[a,""]};
gdocs.TitleComputer.prototype.appendContentTypeExtension_=function(a,b){if(!b||!this.addExtension_)return a;var c=gdocs.EXTENSIONS[b];if(!c)return gdlog.info("TitleComputer.appendContentTypeExtension","No extension mapping for "+b),a;var d=this.splitExtension_(a);return d[1].toLocaleLowerCase()!=c?a+"."+c:d[0]+"."+c};
gdocs.TitleComputer.prototype.unescapeHtml_=function(a){if(!a)return null;a=a.replace(gdocs.TitleComputer.STRIP_META_,"");var b=document.createElement("body");b.innerHTML=a;for(a=b;a.firstChild;)a=a.firstChild;return a.nodeValue};gdocs.TitleComputer.prototype.createDefaultTitle=function(a,b,c,d,e){return 0==c.indexOf(gdocs.MIME_TYPE.HTML)?(e=this.createFromHtml(e))?e:d?this.createNoData_(a,c,b):null:this.createNoData_(a,c,b)};
gdocs.TitleComputer.prototype.createFromHtml=function(a){a=a.match(gdocs.TitleComputer.TITLE_CONTENTS_);return!a||2>a.length?null:this.createTitleFromText(a[1],gdocs.MIME_TYPE.HTML)};
gdocs.TitleComputer.prototype.createNoData_=function(a,b,c){var d=a.lastIndexOf("/");if(d+1==a.length)return c=this.createNoUrlDefaultTitle_(b,c),this.appendContentTypeExtension_(c,b);a=a.substr(d+1);return 0<=a.indexOf("?")||0==a.indexOf("&")?(c=this.createNoUrlDefaultTitle_(b,c),this.appendContentTypeExtension_(c,b)):this.createTitleFromText(decodeURI(a),b)};
gdocs.TitleComputer.prototype.createNoUrlDefaultTitle_=function(a,b){return 0==a.indexOf(gdocs.MIME_TYPE.PDF)?chrome.i18n.getMessage("PDF_DEFAULT_FILENAME"):0==a.indexOf(gdocs.MIME_TYPE.HTML)?chrome.i18n.getMessage("HTML_DEFAULT_FILENAME"):0==a.indexOf(gdocs.MIME_TYPE.XML)?chrome.i18n.getMessage("XML_DEFAULT_FILENAME"):0==a.indexOf("text")?chrome.i18n.getMessage("TEXT_DEFAULT_FILENAME"):0==a.indexOf("video")?chrome.i18n.getMessage("VIDEO_DEFAULT_FILENAME"):0==a.indexOf("audio")?chrome.i18n.getMessage("AUDIO_DEFAULT_FILENAME"):
0==a.indexOf("image")?chrome.i18n.getMessage("IMAGE_DEFAULT_FILENAME"):b};gdocs.DocList=function(a){this.client_=a};gdocs.DocList.Feed={METADATA:gdocs.GOOGLE_DOCS_ROOT_URL+"feeds/metadata/default",UPLOAD_RESUMABLE:gdocs.GOOGLE_DOCS_ROOT_URL+"feeds/upload/create-session/default/private/full/"};gdocs.DocList.addHeaders=function(a){a=a||{};a["GData-Version"]="3.0";a["X-User-Agent"]="google-docschromeextension-1.5";return a};
gdocs.DocList.prototype.loadMetadata=function(a,b){var c=gdocs.DocList.addHeaders();this.getFeed_(gdocs.DocList.Feed.METADATA,c,goog.bind(this.handleMetadataResults_,this,a,b),b)};gdocs.DocList.prototype.handleMetadataResults_=function(a,b,c){c.entry?a(c.entry.author[0].email.$t):b(chrome.i18n.getMessage("USER_INFO_FAILURE"))};
gdocs.DocList.prototype.renameFile=function(a,b,c,d){a=gdocs.DocList.createTitleBody(a);var e=gdocs.DocList.addHeaders({"Content-Type":gdocs.MIME_TYPE.ATOM,"If-Match":"*"});this.putAtomFeed_(b,e,a,goog.bind(this.handleRenameResults_,this,c,d),d)};gdocs.DocList.createTitleBody=function(a){return"<?xml version='1.0' encoding='UTF-8'?>\n<entry xmlns=\"http://www.w3.org/2005/Atom\">\n<title>"+gdocs.xmlEncode(a)+"</title>\n</entry>"};gdocs.DocList.prototype.handleRenameResults_=function(a){a()};
gdocs.DocList.prototype.trashFile=function(a,b,c){var d=gdocs.DocList.addHeaders({"Content-Type":gdocs.MIME_TYPE.ATOM,"If-Match":"*"});this.deleteAtomFeed_(a,d,null,goog.bind(this.handleTrashResults_,this,b),c)};gdocs.DocList.prototype.handleTrashResults_=function(a){a()};gdocs.DocList.prototype.getFeed_=function(a,b,c,d){this.client_.sendRequest("GET",a,{alt:"json"},b,null,goog.bind(this.handleFeedSuccess_,this,c,d),goog.bind(this.handleFeedException_,this,d))};
gdocs.DocList.prototype.putAtomFeed_=function(a,b,c,d,e){this.client_.sendRequest("PUT",a,{alt:"json"},b,c,goog.bind(this.handleFeedSuccess_,this,d,e),goog.bind(this.handleFeedException_,this,e))};gdocs.DocList.prototype.handleFeedSuccess_=function(a,b,c){if(200<=c.status&&202>=c.status){var d=JSON.parse(c.responseText);d?a(d):(a=chrome.i18n.getMessage("DOCS_API_FAILURE",gdocs.createXhrErrMsg(c)),gdlog.warn("DocList.handleFeedSuccess","errMsg:"+a+" responseText:"+c.responseText),b(Error(a)))}else b(Error(gdocs.createXhrErrMsg(c)))};
gdocs.DocList.prototype.handleFeedException_=function(a,b){a(b)};gdocs.DocList.prototype.deleteAtomFeed_=function(a,b,c,d,e){this.client_.sendRequest("DELETE",a,{alt:"json"},b,c,goog.bind(this.handleDeleteSuccess_,this,d,e),goog.bind(this.handleFeedException_,this,e))};gdocs.DocList.prototype.handleDeleteSuccess_=function(a,b,c){200<=c.status&&202>=c.status?a():b(gdocs.createXhrErrMsg(c))};gdocs.domUtil={};gdocs.domUtil.HIDDEN_CLASS_="gdocs-hidden";gdocs.domUtil.getHtmlElementByIdAssert=function(a){var b=document.getElementById(a);if(!b)throw'Could not find Element with id: "'+a+'"';return b};gdocs.domUtil.setTextContent=function(a,b){a.textContent=b};gdocs.domUtil.setTextContentId=function(a,b){var c=document.getElementById(a);c&&gdocs.domUtil.setTextContent(c,b)};gdocs.domUtil.hideElem=function(a){for(var b=0;b<arguments.length;b++)arguments[b].classList.add(gdocs.domUtil.HIDDEN_CLASS_)};
gdocs.domUtil.showElem=function(a){for(var b=0;b<arguments.length;b++)arguments[b].classList.remove(gdocs.domUtil.HIDDEN_CLASS_)};gdocs.UploadStatus=function(a,b,c,d,e,f,g,h){this.dataSource_=a;this.state_=b;this.errorMsg_=c||"";this.sentBytes_=d||0;this.docUrl_=e||"";this.feedUrl_=f||"";this.editUrl_=g||"";this.title_=h||""};gdocs.UploadStatus.STATUS_RESPONSE={CANCEL:"cancel",PROCEED:"proceed"};gdocs.UploadStatus.STATE={FAILURE:"failure",IN_PROGRESS:"inProgress",SUCCESS:"success"};gdocs.UploadStatus.prototype.getDataSource=function(){return this.dataSource_};gdocs.UploadStatus.prototype.getErrorMsg=function(){return this.errorMsg_};
gdocs.UploadStatus.prototype.getSentBytes=function(){return this.sentBytes_};gdocs.UploadStatus.prototype.getDocUrl=function(){return this.docUrl_};gdocs.UploadStatus.prototype.getFeedUrl=function(){return this.feedUrl_};gdocs.UploadStatus.prototype.getEditUrl=function(){return this.editUrl_};gdocs.UploadStatus.prototype.getTitle=function(){return this.title_};gdocs.UploadStatus.prototype.getUploadRatio=function(){return 0==this.sentBytes_?0:this.sentBytes_/this.dataSource_.getSize()};
gdocs.UploadStatus.prototype.isComplete=function(){return this.state_!=gdocs.UploadStatus.STATE.IN_PROGRESS};gdocs.UploadStatus.prototype.isSuccess=function(){return this.state_==gdocs.UploadStatus.STATE.SUCCESS};gdocs.ResumableUploader=function(a,b,c,d,e){this.client_=a;this.dataSource_=b;this.chunkSize_=c;this.extraHeaders_=d||{};this.callback_=e;this.uploadUrl_=null};gdocs.ResumableUploader.RANGE_END_=/\d+-(\d+)/;
gdocs.ResumableUploader.prototype.startResumableUpload=function(){var a=this.patchContentType_(this.dataSource_.getContentType()),b=gdocs.DocList.addHeaders({"Content-Type":gdocs.MIME_TYPE.ATOM,"X-Upload-Content-Type":a,"X-Upload-Content-Length":this.dataSource_.getSize()}),c;for(c in this.extraHeaders_)b[c]=this.extraHeaders_[c];this.dataSource_.getDriveFilename();this.sendFirstPost_(a,b,this.dataSource_.getDriveFilename())};
gdocs.ResumableUploader.prototype.sendFirstPost_=function(a,b,c){var d={alt:"json",convert:this.dataSource_.shouldConvert()},e=gdocs.DocList.Feed.UPLOAD_RESUMABLE;c=gdocs.DocList.createTitleBody(c);gdlog.info("ResumableUploader.sendFirstPost","Starting upload. headers:"+gdlog.prettyPrint(b)+"\nparams:"+gdlog.prettyPrint(d)+"\nbody:"+c);this.client_.sendRequest("POST",e,d,b,c,goog.bind(this.handleStartUploadSuccess_,this,a),goog.bind(this.handleUploadException_,this))};
gdocs.ResumableUploader.prototype.handleStartUploadSuccess_=function(a,b){200==b.status?this.handleResponse_(a,b):(gdlog.info("ResumableUploader.handleStartUploadSuccess",b.status+" failed response: "+b.responseText),this.callback_(null,new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.FAILURE,gdocs.createXhrErrMsg(b))))};
gdocs.ResumableUploader.prototype.handleUploadException_=function(a){gdlog.info("ResumableUploader.handleUploadException",String(a));this.callback_(null,new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.FAILURE,String(a)))};
gdocs.ResumableUploader.prototype.handleResponse_=function(a,b){if(b.status==gdocs.HttpStatus.CREATED)this.handleCreated_(b);else if(b.status!=gdocs.HttpStatus.RESUME_INCOMPLETE&&b.status!=gdocs.HttpStatus.OK){var c=gdocs.createXhrErrMsg(b);gdlog.info("ResumableUploader.handleResponse","responseText:"+b.responseText+" url:"+this.uploadUrl_+" errMsg:"+c);this.callback_(null,new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.FAILURE,c))}else{this.uploadUrl_=b.getResponseHeader("Location")||
this.uploadUrl_;gdlog.fine("ResumableUploader.handleResponse","Continuing upload of "+this.uploadUrl_);var c=(c=b.getResponseHeader("Range"))?Number(c.match(gdocs.ResumableUploader.RANGE_END_)[1])+1:0,d=this.dataSource_.getSize(),e=Math.min(d,c+this.chunkSize_)-1,f=new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.IN_PROGRESS,null,Math.max(0,c-1));(f=this.callback_(null,f))&&f==gdocs.UploadStatus.STATUS_RESPONSE.CANCEL?(c=chrome.i18n.getMessage("UPLOAD_CANCELED"),this.callback_(null,
new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.FAILURE,c))):(d={"Content-Type":a,"Content-Range":"bytes "+c+"-"+e+"/"+d},c=this.dataSource_.getData(c,e+1),gdlog.info("ResumableUploader.handleResponse","Sending "+d["Content-Range"]),this.client_.sendRequest("PUT",this.uploadUrl_,null,d,c,goog.bind(this.handleResponse_,this,a),goog.bind(this.handleUploadException_,this),!0))}};
gdocs.ResumableUploader.prototype.handleCreated_=function(a){gdlog.info("ResumableUploader.handleCreated",this.uploadUrl_+" completed with status:"+a.status);for(var b=JSON.parse(a.responseText).entry,c,d,e,f=b.link.length,g=0;g<f;g++){var h=b.link[g];"alternate"==h.rel&&"text/html"==h.type?c=h.href:"self"==h.rel?d=h.href:"edit"==h.rel&&(e=h.href)}b=b.title.$t;this.callback_(a.responseText,new gdocs.UploadStatus(this.dataSource_,gdocs.UploadStatus.STATE.SUCCESS,null,this.dataSource_.getSize(),c,d,
e,b))};gdocs.ResumableUploader.prototype.patchContentType_=function(a){var b=a;if(b){var c=b.indexOf(";");0<=c&&(b=b.substring(0,c));b=b.toLowerCase();0==b.indexOf(gdocs.MIME_TYPE.X_PDF)&&(b=gdocs.MIME_TYPE.PDF)}else b=gdocs.MIME_TYPE.OCTET_STREAM;b!=a&&gdlog.info("ResumableUploader.patchContentType","Changing Content-Type from "+a+" to "+b);return b};gdocs.Uploader=function(a,b,c){this.client_=a;this.uploadPage_=b;this.uploadParams_=this.uploadPage_.getUploadParams();this.dataSource_=c;this.startPercent_=this.uploadParams_.isUploadOnly()?0:50};gdocs.Uploader.prototype.startUploadWhenReady=function(){this.uploadDataSourceWhenReady_(this.dataSource_)};
gdocs.Uploader.prototype.uploadDataSourceWhenReady_=function(a){var b=new gdocs.ResumableUploader(this.client_,a,gdocs.UPLOAD_CHUNK_SIZE,gdocs.impressionHeader(this.uploadParams_.getUserImpression()),goog.bind(this.uploadCallback_,this,a));a.startWhenReady(b)};
gdocs.Uploader.prototype.uploadCallback_=function(a,b,c){this.setStartFileMsg_(a.getDriveFilename());a=this.uploadPage_.isCancel()?gdocs.UploadStatus.STATUS_RESPONSE.CANCEL:gdocs.UploadStatus.STATUS_RESPONSE.PROCEED;if(!c.isComplete())return c=c.getUploadRatio(),this.uploadPage_.setPercent(this.startPercent_+(100-this.startPercent_)*c),a;if(!c.isSuccess())return c=chrome.i18n.getMessage("UPLOAD_FAILURE",[c.getErrorMsg()]),this.uploadPage_.fatal(c,!1),a;this.uploadPage_.showFinished(c);return a};
gdocs.Uploader.prototype.setStartFileMsg_=function(a){this.uploadPage_.setPercent(this.startPercent_);a=this.uploadParams_.isUploadOnly()?chrome.i18n.getMessage("UPLOADING",a):chrome.i18n.getMessage("SAVING",a);this.uploadPage_.updateProgressText(a)};gdocs.UploadPage=function(a,b){this.client_=a;this.docList_=new gdocs.DocList(a);this.uploadParams_=b;this.uploadStatus_=null;this.lastFilename_="";this.progressContainerEl_=gdocs.domUtil.getHtmlElementByIdAssert("progress-container");this.resultsContainerEl_=gdocs.domUtil.getHtmlElementByIdAssert("results-container");this.renameContainerEl_=gdocs.domUtil.getHtmlElementByIdAssert("rename-container");this.errorContainerEl_=gdocs.domUtil.getHtmlElementByIdAssert("error-container");this.userIdEl_=gdocs.domUtil.getHtmlElementByIdAssert("user-id");
this.progressTextEl_=gdocs.domUtil.getHtmlElementByIdAssert("progress-text");this.percentEl_=gdocs.domUtil.getHtmlElementByIdAssert("percent");this.uploadProgressEl_=gdocs.domUtil.getHtmlElementByIdAssert("upload-progress");this.resultsTextEl_=gdocs.domUtil.getHtmlElementByIdAssert("results-text");this.errorTextEl_=gdocs.domUtil.getHtmlElementByIdAssert("error-text");this.renameInputEl_=gdocs.domUtil.getHtmlElementByIdAssert("rename-input");this.renameInputEl_.addEventListener("keyup",goog.bind(this.handleRenameInputChanged_,
this),!1);this.cancelButtonEl_=this.setupDivButton_("cancel-button",chrome.i18n.getMessage("CANCEL"),goog.bind(this.handleCancel_,this));this.applyButtonEl_=this.setupDivButton_("apply-button",chrome.i18n.getMessage("APPLY"),goog.bind(this.handleApply_,this));this.closeButtonEl_=this.setupDivButton_("close-button",chrome.i18n.getMessage("CLOSE"),goog.bind(this.handleClose_,this));this.renameButtonEl_=this.setupDivButton_("rename-button",chrome.i18n.getMessage("RENAME"),goog.bind(this.handleRename_,
this));this.trashButtonEl_=this.setupDivButton_("trash-button",chrome.i18n.getMessage("TRASH"),goog.bind(this.trash_,this));this.currentContainerEl_=this.progressContainerEl_;this.cancel_=!1;gdocs.domUtil.setTextContentId("dialog-title",chrome.i18n.getMessage("CHROME_EXTENSION_NAME"));gdocs.domUtil.setTextContentId("product-name",chrome.i18n.getMessage("GOOGLE_DRIVE"));gdocs.domUtil.setTextContentId("rename-text",chrome.i18n.getMessage("RENAME_PROMPT"));window.addEventListener("keyup",goog.bind(this.handleDialogKeyUp_,
this),!1)};gdocs.UploadPage.ENTER_KEY_=13;gdocs.UploadPage.SPACE_KEY_=32;gdocs.UploadPage.JFK_BUTTON_DISABLED_CLASS_="jfk-button-disabled";gdocs.UploadPage.prototype.getUploadParams=function(){return this.uploadParams_};gdocs.UploadPage.prototype.startLoading=function(a){a.getUserId().getUserIdStr(goog.bind(this.setUserId_,this));(new gdocs.Uploader(this.client_,this,this.createDataSource())).startUploadWhenReady()};gdocs.UploadPage.prototype.isCancel=function(){return this.cancel_};
gdocs.UploadPage.prototype.clearCancel=function(){this.cancel_=!1;this.setButtonState_(this.cancelButtonEl_,!0)};
gdocs.UploadPage.prototype.setupDivButton_=function(a,b,c){var d=gdocs.domUtil.getHtmlElementByIdAssert(a);gdocs.domUtil.setTextContent(d,b);d.addEventListener("click",function(){d.classList.contains(gdocs.UploadPage.JFK_BUTTON_DISABLED_CLASS_)||c()},!1);d.addEventListener("keyup",function(a){gdocs.UploadPage.isApply_(a)&&(d.classList.contains(gdocs.UploadPage.JFK_BUTTON_DISABLED_CLASS_)||c())},!1);return d};
gdocs.UploadPage.prototype.setButtonState_=function(a,b){b?a.classList.remove(gdocs.UploadPage.JFK_BUTTON_DISABLED_CLASS_):a.classList.add(gdocs.UploadPage.JFK_BUTTON_DISABLED_CLASS_)};gdocs.UploadPage.prototype.setUserId_=function(a){gdocs.domUtil.setTextContent(this.userIdEl_,a)};gdocs.UploadPage.prototype.handleDialogKeyUp_=function(a){a.keyCode==gdocs.KEYCODE_ESCAPE&&this.handleClose_()};
gdocs.UploadPage.prototype.handleRenameInputChanged_=function(a){var b=0<this.renameInputEl_.value.length&&this.renameInputEl_.value!=this.lastFilename_;this.setButtonState_(this.applyButtonEl_,b);b&&a.keyCode==gdocs.UploadPage.ENTER_KEY_&&this.handleApply_()};gdocs.UploadPage.isApply_=function(a){return a.keyCode==gdocs.UploadPage.ENTER_KEY_||a.keyCode==gdocs.UploadPage.SPACE_KEY_};
gdocs.UploadPage.prototype.handleApply_=function(){this.setButtonState_(this.applyButtonEl_,!1);var a=this.renameInputEl_.value.replace(/^\s+|\s+$/,"");this.docList_.renameFile(a,this.uploadStatus_.getEditUrl(),goog.bind(this.handleRenameFileSuccess_,this,a),goog.bind(this.handleRenameFileFailure_,this))};
gdocs.UploadPage.prototype.handleRenameFileSuccess_=function(a){this.lastFilename_=a;this.setSingleFileFinalResults_();gdocs.domUtil.hideElem(this.applyButtonEl_,this.cancelButtonEl_);gdocs.domUtil.showElem(this.closeButtonEl_,this.renameButtonEl_,this.trashButtonEl_);this.display_(this.resultsContainerEl_)};gdocs.UploadPage.prototype.handleRenameFileFailure_=function(a){this.setButtonState_(this.applyButtonEl_,!0);this.displayError_(a)};gdocs.UploadPage.prototype.displayError_=function(a){this.displayErrorMsg_(String(a))};
gdocs.UploadPage.prototype.displayErrorMsg_=function(a){gdocs.domUtil.setTextContent(this.errorTextEl_,a);this.display_(this.errorContainerEl_)};gdocs.UploadPage.prototype.displayErrorMsgHtml_=function(a){this.errorContainerEl_.innerHTML=a;this.display_(this.errorContainerEl_)};gdocs.UploadPage.prototype.updateProgressText=function(a){gdocs.domUtil.setTextContent(this.progressTextEl_,a);this.display_(this.progressContainerEl_)};
gdocs.UploadPage.prototype.setPercent=function(a){a=String(Math.floor(a));this.uploadProgressEl_.value=a;gdocs.domUtil.setTextContent(this.percentEl_,chrome.i18n.getMessage("PERCENT",a))};gdocs.UploadPage.prototype.fatal=function(a,b){b?this.displayErrorMsgHtml_(a):this.displayErrorMsg_(a);gdocs.domUtil.hideElem(this.cancelButtonEl_);gdocs.domUtil.showElem(this.closeButtonEl_)};
gdocs.UploadPage.prototype.showFinished=function(a){this.uploadStatus_=a;this.lastFilename_=a.getTitle();this.setSingleFileFinalResults_();gdocs.domUtil.showElem(this.renameButtonEl_,this.trashButtonEl_);gdocs.domUtil.hideElem(this.cancelButtonEl_);gdocs.domUtil.showElem(this.closeButtonEl_);this.display_(this.resultsContainerEl_)};
gdocs.UploadPage.prototype.setSingleFileFinalResults_=function(){this.resultsTextEl_.innerHTML=chrome.i18n.getMessage("FILE_WAS_SAVED",["file-link",this.uploadStatus_.getDocUrl(),gdocs.xmlEncode(this.lastFilename_),"docs-link",this.createDocListUrl_()]);this.addCloseFromLinkHandler_("file-link");this.addCloseFromLinkHandler_("docs-link")};
gdocs.UploadPage.prototype.addCloseFromLinkHandler_=function(a){gdocs.domUtil.getHtmlElementByIdAssert(a).addEventListener("click",goog.bind(this.handleClose_,this),!1)};gdocs.UploadPage.prototype.createDocListUrl_=function(){return gdocs.GOOGLE_DOCS_ROOT_URL+"#search/title:"+encodeURIComponent('"'+this.lastFilename_+'"')};
gdocs.UploadPage.prototype.handleCancel_=function(){this.currentContainerEl_==this.renameContainerEl_?(gdocs.domUtil.hideElem(this.applyButtonEl_,this.cancelButtonEl_),gdocs.domUtil.showElem(this.closeButtonEl_,this.renameButtonEl_,this.trashButtonEl_),this.display_(this.resultsContainerEl_)):(this.cancel_=!0,this.setButtonState_(this.cancelButtonEl_,!1))};gdocs.UploadPage.prototype.handleClose_=function(){this.cancel_=!0;window.close()};
gdocs.UploadPage.prototype.handleRename_=function(){this.renameInputEl_.value=this.lastFilename_;this.display_(this.renameContainerEl_);gdocs.domUtil.hideElem(this.closeButtonEl_,this.renameButtonEl_,this.trashButtonEl_);gdocs.domUtil.showElem(this.applyButtonEl_,this.cancelButtonEl_);this.setButtonState_(this.applyButtonEl_,!1);this.renameInputEl_.focus();this.renameInputEl_.select();var a=this.lastFilename_.lastIndexOf(".");-1!=a&&this.lastFilename_.length-(a+1)<=gdocs.MAX_SUFFIX_LEN&&(this.renameInputEl_.selectionEnd=
a)};gdocs.UploadPage.prototype.display_=function(a){gdocs.domUtil.hideElem(this.currentContainerEl_);gdocs.domUtil.showElem(a);this.currentContainerEl_=a};gdocs.UploadPage.prototype.trash_=function(){this.setButtonState_(this.trashButtonEl_,!1);this.setButtonState_(this.renameButtonEl_,!1);this.docList_.trashFile(this.uploadStatus_.getEditUrl(),goog.bind(this.handleTrashSuccess_,this),goog.bind(this.handleTrashFailure_,this))};
gdocs.UploadPage.prototype.handleTrashSuccess_=function(){this.resultsTextEl_.innerHTML=chrome.i18n.getMessage("FILE_WAS_TRASHED",[gdocs.xmlEncode(this.lastFilename_),"docs-link",gdocs.GOOGLE_DOCS_ROOT_URL]);this.addCloseFromLinkHandler_("docs-link");this.display_(this.resultsContainerEl_);gdocs.domUtil.hideElem(this.cancelButtonEl_,this.renameButtonEl_,this.trashButtonEl_)};
gdocs.UploadPage.prototype.handleTrashFailure_=function(a){this.setButtonState_(this.trashButtonEl_,!0);this.setButtonState_(this.renameButtonEl_,!0);this.displayError_(a)};gdocs.BlobUploadPage=function(a,b){gdocs.UploadPage.call(this,a,b)};goog.inherits(gdocs.BlobUploadPage,gdocs.UploadPage);gdocs.BlobUploadPage.prototype.createDataSource=function(){var a=this.getUploadParams(),b=(new gdocs.TitleComputer(gdocs.MAX_GENERATED_TITLE_LEN,gdocs.MAX_SUFFIX_LEN,!0)).createTitleFromText(a.getSuggestedFilename(),a.getContentType());b||(b=chrome.i18n.getMessage("DEFAULT_FILENAME"));return new gdocs.BlobDataSource(a.getBlob(),a.getAllowConvert(),b,a.getContentType())};gdocs.CaptureDataSource=function(a){gdocs.DataSource.call(this);this.capturer_=a};goog.inherits(gdocs.CaptureDataSource,gdocs.DataSource);gdocs.CaptureDataSource.prototype.shouldConvert=function(){return this.capturer_.getAllowConvert()&&this.getContentType()in gdocs.CONVERTIBLE};gdocs.CaptureDataSource.prototype.getDriveFilename=function(){return this.capturer_.getFilename()};
gdocs.CaptureDataSource.prototype.startWhenReady=function(a){null!=this.capturer_.getDownloadResults()?a.startResumableUpload():this.capturer_.setResumableUploader(a)};gdocs.CaptureDataSource.prototype.getContentType=function(){return this.capturer_.getDownloadResults().getContentType()};gdocs.CaptureDataSource.prototype.getSize=function(){return this.capturer_.getDownloadResults().getBlobData().size};
gdocs.CaptureDataSource.prototype.getData=function(a,b){return this.capturer_.getDownloadResults().getBlobData().slice(a,b)};gdocs.CaptureUploadPage=function(a,b){gdocs.UploadPage.call(this,a,b)};goog.inherits(gdocs.CaptureUploadPage,gdocs.UploadPage);gdocs.CaptureUploadPage.prototype.createDataSource=function(){var a=this.getUploadParams();a.getCapturer().setUploadPage(this);return new gdocs.CaptureDataSource(a.getCapturer())};gdocs.UrlDataSource=function(a){gdocs.DataSource.call(this);this.urlDownloader_=a};goog.inherits(gdocs.UrlDataSource,gdocs.DataSource);gdocs.UrlDataSource.prototype.getDriveFilename=function(){return this.urlDownloader_.getFilename()};gdocs.UrlDataSource.prototype.startWhenReady=function(a){this.urlDownloader_.hasFailed()||(null!=this.urlDownloader_.getDownloadResults()?a.startResumableUpload():this.urlDownloader_.setResumableUploader(a))};gdocs.UrlDataSource.prototype.getContentType=function(){return this.urlDownloader_.getDownloadResults().getContentType()};
gdocs.UrlDataSource.prototype.shouldConvert=function(){return this.urlDownloader_.getAllowConvert()&&this.getContentType()in gdocs.CONVERTIBLE};gdocs.UrlDataSource.prototype.getSize=function(){return this.urlDownloader_.getDownloadResults().getBlobData().size};gdocs.UrlDataSource.prototype.getData=function(a,b){return this.urlDownloader_.getDownloadResults().getBlobData().slice(a,b)};gdocs.UrlUploadPage=function(a,b){gdocs.UploadPage.call(this,a,b)};goog.inherits(gdocs.UrlUploadPage,gdocs.UploadPage);gdocs.UrlUploadPage.prototype.createDataSource=function(){var a=this.getUploadParams();a.getUrlDownloader().setUploadPage(this);return new gdocs.UrlDataSource(a.getUrlDownloader())};window.addEventListener("load",function(){var a=chrome.extension.getBackgroundPage().bg;gdlog.loglevel=a.getLogLevel();var b=a.getUploadParams();(b.getBlob?new gdocs.BlobUploadPage(a.getClient(),b):b.getCapturer?new gdocs.CaptureUploadPage(a.getClient(),b):new gdocs.UrlUploadPage(a.getClient(),b)).startLoading(a)},!1);
